# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ryan1/OneDrive/Desktop/ECE350_Workspace/ECE350Labs/Sobel_Lab_Miller_RTL/Sobel_Lab_Miller_RTL.srcs/sources_1/bd/design_1/ip/design_1_sobel_rgb_axis_0_0/design_1_sobel_rgb_axis_0_0.xci
# IP: The module: 'design_1_sobel_rgb_axis_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ryan1/OneDrive/Desktop/ECE350_Workspace/ECE350Labs/Sobel_Lab_Miller_RTL/Sobel_Lab_Miller_RTL.srcs/sources_1/bd/design_1/ip/design_1_sobel_rgb_axis_0_0/constraints/sobel_rgb_axis_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sobel_rgb_axis_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/ryan1/OneDrive/Desktop/ECE350_Workspace/ECE350Labs/Sobel_Lab_Miller_RTL/Sobel_Lab_Miller_RTL.srcs/sources_1/bd/design_1/ip/design_1_sobel_rgb_axis_0_0/design_1_sobel_rgb_axis_0_0.xci
# IP: The module: 'design_1_sobel_rgb_axis_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ryan1/OneDrive/Desktop/ECE350_Workspace/ECE350Labs/Sobel_Lab_Miller_RTL/Sobel_Lab_Miller_RTL.srcs/sources_1/bd/design_1/ip/design_1_sobel_rgb_axis_0_0/constraints/sobel_rgb_axis_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sobel_rgb_axis_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
