#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("mat_a_0_0", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("mat_a_0_1", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("mat_a_1_0", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("mat_a_1_1", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("mat_b_0_0", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("mat_b_0_1", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("mat_b_1_0", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("mat_b_1_1", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("mat_c_0_0", 32, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("mat_c_0_0_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("mat_c_0_1", 32, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("mat_c_0_1_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("mat_c_1_0", 32, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("mat_c_1_0_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("mat_c_1_1", 32, hls_out, 11, "ap_vld", "out_data", 1),
	Port_Property("mat_c_1_1_ap_vld", 1, hls_out, 11, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "matrix_mult";
