// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _matrix_mult_HH_
#define _matrix_mult_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct matrix_mult : public sc_module {
    // Port declarations 22
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > mat_a_0_0;
    sc_in< sc_lv<32> > mat_a_0_1;
    sc_in< sc_lv<32> > mat_a_1_0;
    sc_in< sc_lv<32> > mat_a_1_1;
    sc_in< sc_lv<32> > mat_b_0_0;
    sc_in< sc_lv<32> > mat_b_0_1;
    sc_in< sc_lv<32> > mat_b_1_0;
    sc_in< sc_lv<32> > mat_b_1_1;
    sc_out< sc_lv<32> > mat_c_0_0;
    sc_out< sc_logic > mat_c_0_0_ap_vld;
    sc_out< sc_lv<32> > mat_c_0_1;
    sc_out< sc_logic > mat_c_0_1_ap_vld;
    sc_out< sc_lv<32> > mat_c_1_0;
    sc_out< sc_logic > mat_c_1_0_ap_vld;
    sc_out< sc_lv<32> > mat_c_1_1;
    sc_out< sc_logic > mat_c_1_1_ap_vld;


    // Module declarations
    matrix_mult(sc_module_name name);
    SC_HAS_PROCESS(matrix_mult);

    ~matrix_mult();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<2> > r_fu_189_p2;
    sc_signal< sc_lv<2> > r_reg_284;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > trunc_ln32_fu_195_p1;
    sc_signal< sc_lv<1> > trunc_ln32_reg_289;
    sc_signal< sc_lv<1> > icmp_ln26_fu_183_p2;
    sc_signal< sc_lv<2> > c_fu_205_p2;
    sc_signal< sc_lv<2> > c_reg_297;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln28_fu_199_p2;
    sc_signal< sc_lv<1> > trunc_ln32_1_fu_211_p1;
    sc_signal< sc_lv<1> > trunc_ln32_1_reg_312;
    sc_signal< sc_lv<32> > select_ln32_2_fu_215_p3;
    sc_signal< sc_lv<32> > select_ln32_2_reg_326;
    sc_signal< sc_lv<32> > select_ln32_3_fu_223_p3;
    sc_signal< sc_lv<32> > select_ln32_3_reg_331;
    sc_signal< sc_lv<2> > p_fu_237_p2;
    sc_signal< sc_lv<2> > p_reg_339;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > select_ln32_4_fu_259_p3;
    sc_signal< sc_lv<32> > select_ln32_4_reg_344;
    sc_signal< sc_lv<1> > icmp_ln31_fu_231_p2;
    sc_signal< sc_lv<32> > select_ln32_5_fu_266_p3;
    sc_signal< sc_lv<32> > select_ln32_5_reg_349;
    sc_signal< sc_lv<32> > mul_ln32_fu_272_p2;
    sc_signal< sc_lv<32> > mul_ln32_reg_354;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > sum_fu_276_p2;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<2> > r_0_reg_134;
    sc_signal< sc_lv<2> > c_0_reg_145;
    sc_signal< sc_lv<32> > sum_0_reg_156;
    sc_signal< sc_lv<2> > p_0_reg_172;
    sc_signal< sc_lv<1> > trunc_ln32_2_fu_243_p1;
    sc_signal< sc_lv<32> > select_ln32_fu_247_p3;
    sc_signal< sc_lv<32> > select_ln32_1_fu_253_p3;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_c_fu_205_p2();
    void thread_icmp_ln26_fu_183_p2();
    void thread_icmp_ln28_fu_199_p2();
    void thread_icmp_ln31_fu_231_p2();
    void thread_mat_c_0_0();
    void thread_mat_c_0_0_ap_vld();
    void thread_mat_c_0_1();
    void thread_mat_c_0_1_ap_vld();
    void thread_mat_c_1_0();
    void thread_mat_c_1_0_ap_vld();
    void thread_mat_c_1_1();
    void thread_mat_c_1_1_ap_vld();
    void thread_mul_ln32_fu_272_p2();
    void thread_p_fu_237_p2();
    void thread_r_fu_189_p2();
    void thread_select_ln32_1_fu_253_p3();
    void thread_select_ln32_2_fu_215_p3();
    void thread_select_ln32_3_fu_223_p3();
    void thread_select_ln32_4_fu_259_p3();
    void thread_select_ln32_5_fu_266_p3();
    void thread_select_ln32_fu_247_p3();
    void thread_sum_fu_276_p2();
    void thread_trunc_ln32_1_fu_211_p1();
    void thread_trunc_ln32_2_fu_243_p1();
    void thread_trunc_ln32_fu_195_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
