// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrix_mult.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_mult::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_mult::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> matrix_mult::ap_ST_fsm_state1 = "1";
const sc_lv<6> matrix_mult::ap_ST_fsm_state2 = "10";
const sc_lv<6> matrix_mult::ap_ST_fsm_state3 = "100";
const sc_lv<6> matrix_mult::ap_ST_fsm_state4 = "1000";
const sc_lv<6> matrix_mult::ap_ST_fsm_state5 = "10000";
const sc_lv<6> matrix_mult::ap_ST_fsm_state6 = "100000";
const sc_lv<32> matrix_mult::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> matrix_mult::ap_const_lv32_1 = "1";
const sc_lv<1> matrix_mult::ap_const_lv1_0 = "0";
const sc_lv<32> matrix_mult::ap_const_lv32_2 = "10";
const sc_lv<32> matrix_mult::ap_const_lv32_3 = "11";
const sc_lv<32> matrix_mult::ap_const_lv32_4 = "100";
const sc_lv<32> matrix_mult::ap_const_lv32_5 = "101";
const sc_lv<2> matrix_mult::ap_const_lv2_0 = "00";
const sc_lv<1> matrix_mult::ap_const_lv1_1 = "1";
const sc_lv<2> matrix_mult::ap_const_lv2_2 = "10";
const sc_lv<2> matrix_mult::ap_const_lv2_1 = "1";
const bool matrix_mult::ap_const_boolean_1 = true;

matrix_mult::matrix_mult(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln26_fu_183_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln26_fu_183_p2 );

    SC_METHOD(thread_c_fu_205_p2);
    sensitive << ( c_0_reg_145 );

    SC_METHOD(thread_icmp_ln26_fu_183_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_0_reg_134 );

    SC_METHOD(thread_icmp_ln28_fu_199_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( c_0_reg_145 );

    SC_METHOD(thread_icmp_ln31_fu_231_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_0_reg_172 );

    SC_METHOD(thread_mat_c_0_0);
    sensitive << ( trunc_ln32_reg_289 );
    sensitive << ( trunc_ln32_1_reg_312 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln31_fu_231_p2 );
    sensitive << ( sum_0_reg_156 );

    SC_METHOD(thread_mat_c_0_0_ap_vld);
    sensitive << ( trunc_ln32_reg_289 );
    sensitive << ( trunc_ln32_1_reg_312 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln31_fu_231_p2 );

    SC_METHOD(thread_mat_c_0_1);
    sensitive << ( trunc_ln32_reg_289 );
    sensitive << ( trunc_ln32_1_reg_312 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln31_fu_231_p2 );
    sensitive << ( sum_0_reg_156 );

    SC_METHOD(thread_mat_c_0_1_ap_vld);
    sensitive << ( trunc_ln32_reg_289 );
    sensitive << ( trunc_ln32_1_reg_312 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln31_fu_231_p2 );

    SC_METHOD(thread_mat_c_1_0);
    sensitive << ( trunc_ln32_reg_289 );
    sensitive << ( trunc_ln32_1_reg_312 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln31_fu_231_p2 );
    sensitive << ( sum_0_reg_156 );

    SC_METHOD(thread_mat_c_1_0_ap_vld);
    sensitive << ( trunc_ln32_reg_289 );
    sensitive << ( trunc_ln32_1_reg_312 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln31_fu_231_p2 );

    SC_METHOD(thread_mat_c_1_1);
    sensitive << ( trunc_ln32_reg_289 );
    sensitive << ( trunc_ln32_1_reg_312 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln31_fu_231_p2 );
    sensitive << ( sum_0_reg_156 );

    SC_METHOD(thread_mat_c_1_1_ap_vld);
    sensitive << ( trunc_ln32_reg_289 );
    sensitive << ( trunc_ln32_1_reg_312 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln31_fu_231_p2 );

    SC_METHOD(thread_mul_ln32_fu_272_p2);
    sensitive << ( select_ln32_4_reg_344 );
    sensitive << ( select_ln32_5_reg_349 );

    SC_METHOD(thread_p_fu_237_p2);
    sensitive << ( p_0_reg_172 );

    SC_METHOD(thread_r_fu_189_p2);
    sensitive << ( r_0_reg_134 );

    SC_METHOD(thread_select_ln32_1_fu_253_p3);
    sensitive << ( mat_a_0_0 );
    sensitive << ( mat_a_0_1 );
    sensitive << ( trunc_ln32_2_fu_243_p1 );

    SC_METHOD(thread_select_ln32_2_fu_215_p3);
    sensitive << ( mat_b_1_0 );
    sensitive << ( mat_b_1_1 );
    sensitive << ( trunc_ln32_1_fu_211_p1 );

    SC_METHOD(thread_select_ln32_3_fu_223_p3);
    sensitive << ( mat_b_0_0 );
    sensitive << ( mat_b_0_1 );
    sensitive << ( trunc_ln32_1_fu_211_p1 );

    SC_METHOD(thread_select_ln32_4_fu_259_p3);
    sensitive << ( trunc_ln32_reg_289 );
    sensitive << ( select_ln32_fu_247_p3 );
    sensitive << ( select_ln32_1_fu_253_p3 );

    SC_METHOD(thread_select_ln32_5_fu_266_p3);
    sensitive << ( select_ln32_2_reg_326 );
    sensitive << ( select_ln32_3_reg_331 );
    sensitive << ( trunc_ln32_2_fu_243_p1 );

    SC_METHOD(thread_select_ln32_fu_247_p3);
    sensitive << ( mat_a_1_0 );
    sensitive << ( mat_a_1_1 );
    sensitive << ( trunc_ln32_2_fu_243_p1 );

    SC_METHOD(thread_sum_fu_276_p2);
    sensitive << ( mul_ln32_reg_354 );
    sensitive << ( sum_0_reg_156 );

    SC_METHOD(thread_trunc_ln32_1_fu_211_p1);
    sensitive << ( c_0_reg_145 );

    SC_METHOD(thread_trunc_ln32_2_fu_243_p1);
    sensitive << ( p_0_reg_172 );

    SC_METHOD(thread_trunc_ln32_fu_195_p1);
    sensitive << ( r_0_reg_134 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln26_fu_183_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln28_fu_199_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln31_fu_231_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_mult_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, mat_a_0_0, "(port)mat_a_0_0");
    sc_trace(mVcdFile, mat_a_0_1, "(port)mat_a_0_1");
    sc_trace(mVcdFile, mat_a_1_0, "(port)mat_a_1_0");
    sc_trace(mVcdFile, mat_a_1_1, "(port)mat_a_1_1");
    sc_trace(mVcdFile, mat_b_0_0, "(port)mat_b_0_0");
    sc_trace(mVcdFile, mat_b_0_1, "(port)mat_b_0_1");
    sc_trace(mVcdFile, mat_b_1_0, "(port)mat_b_1_0");
    sc_trace(mVcdFile, mat_b_1_1, "(port)mat_b_1_1");
    sc_trace(mVcdFile, mat_c_0_0, "(port)mat_c_0_0");
    sc_trace(mVcdFile, mat_c_0_0_ap_vld, "(port)mat_c_0_0_ap_vld");
    sc_trace(mVcdFile, mat_c_0_1, "(port)mat_c_0_1");
    sc_trace(mVcdFile, mat_c_0_1_ap_vld, "(port)mat_c_0_1_ap_vld");
    sc_trace(mVcdFile, mat_c_1_0, "(port)mat_c_1_0");
    sc_trace(mVcdFile, mat_c_1_0_ap_vld, "(port)mat_c_1_0_ap_vld");
    sc_trace(mVcdFile, mat_c_1_1, "(port)mat_c_1_1");
    sc_trace(mVcdFile, mat_c_1_1_ap_vld, "(port)mat_c_1_1_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, r_fu_189_p2, "r_fu_189_p2");
    sc_trace(mVcdFile, r_reg_284, "r_reg_284");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, trunc_ln32_fu_195_p1, "trunc_ln32_fu_195_p1");
    sc_trace(mVcdFile, trunc_ln32_reg_289, "trunc_ln32_reg_289");
    sc_trace(mVcdFile, icmp_ln26_fu_183_p2, "icmp_ln26_fu_183_p2");
    sc_trace(mVcdFile, c_fu_205_p2, "c_fu_205_p2");
    sc_trace(mVcdFile, c_reg_297, "c_reg_297");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln28_fu_199_p2, "icmp_ln28_fu_199_p2");
    sc_trace(mVcdFile, trunc_ln32_1_fu_211_p1, "trunc_ln32_1_fu_211_p1");
    sc_trace(mVcdFile, trunc_ln32_1_reg_312, "trunc_ln32_1_reg_312");
    sc_trace(mVcdFile, select_ln32_2_fu_215_p3, "select_ln32_2_fu_215_p3");
    sc_trace(mVcdFile, select_ln32_2_reg_326, "select_ln32_2_reg_326");
    sc_trace(mVcdFile, select_ln32_3_fu_223_p3, "select_ln32_3_fu_223_p3");
    sc_trace(mVcdFile, select_ln32_3_reg_331, "select_ln32_3_reg_331");
    sc_trace(mVcdFile, p_fu_237_p2, "p_fu_237_p2");
    sc_trace(mVcdFile, p_reg_339, "p_reg_339");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, select_ln32_4_fu_259_p3, "select_ln32_4_fu_259_p3");
    sc_trace(mVcdFile, select_ln32_4_reg_344, "select_ln32_4_reg_344");
    sc_trace(mVcdFile, icmp_ln31_fu_231_p2, "icmp_ln31_fu_231_p2");
    sc_trace(mVcdFile, select_ln32_5_fu_266_p3, "select_ln32_5_fu_266_p3");
    sc_trace(mVcdFile, select_ln32_5_reg_349, "select_ln32_5_reg_349");
    sc_trace(mVcdFile, mul_ln32_fu_272_p2, "mul_ln32_fu_272_p2");
    sc_trace(mVcdFile, mul_ln32_reg_354, "mul_ln32_reg_354");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, sum_fu_276_p2, "sum_fu_276_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, r_0_reg_134, "r_0_reg_134");
    sc_trace(mVcdFile, c_0_reg_145, "c_0_reg_145");
    sc_trace(mVcdFile, sum_0_reg_156, "sum_0_reg_156");
    sc_trace(mVcdFile, p_0_reg_172, "p_0_reg_172");
    sc_trace(mVcdFile, trunc_ln32_2_fu_243_p1, "trunc_ln32_2_fu_243_p1");
    sc_trace(mVcdFile, select_ln32_fu_247_p3, "select_ln32_fu_247_p3");
    sc_trace(mVcdFile, select_ln32_1_fu_253_p3, "select_ln32_1_fu_253_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("matrix_mult.hdltvin.dat");
    mHdltvoutHandle.open("matrix_mult.hdltvout.dat");
}

matrix_mult::~matrix_mult() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void matrix_mult::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_231_p2.read(), ap_const_lv1_1))) {
        c_0_reg_145 = c_reg_297.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln26_fu_183_p2.read(), ap_const_lv1_0))) {
        c_0_reg_145 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_0_reg_172 = p_reg_339.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln28_fu_199_p2.read()))) {
        p_0_reg_172 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln28_fu_199_p2.read(), ap_const_lv1_1))) {
        r_0_reg_134 = r_reg_284.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        r_0_reg_134 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        sum_0_reg_156 = sum_fu_276_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln28_fu_199_p2.read()))) {
        sum_0_reg_156 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        c_reg_297 = c_fu_205_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mul_ln32_reg_354 = mul_ln32_fu_272_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_reg_339 = p_fu_237_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        r_reg_284 = r_fu_189_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln28_fu_199_p2.read()))) {
        select_ln32_2_reg_326 = select_ln32_2_fu_215_p3.read();
        select_ln32_3_reg_331 = select_ln32_3_fu_223_p3.read();
        trunc_ln32_1_reg_312 = trunc_ln32_1_fu_211_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln31_fu_231_p2.read()))) {
        select_ln32_4_reg_344 = select_ln32_4_fu_259_p3.read();
        select_ln32_5_reg_349 = select_ln32_5_fu_266_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln26_fu_183_p2.read(), ap_const_lv1_0))) {
        trunc_ln32_reg_289 = trunc_ln32_fu_195_p1.read();
    }
}

void matrix_mult::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void matrix_mult::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void matrix_mult::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void matrix_mult::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void matrix_mult::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void matrix_mult::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void matrix_mult::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln26_fu_183_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrix_mult::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrix_mult::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln26_fu_183_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrix_mult::thread_c_fu_205_p2() {
    c_fu_205_p2 = (!c_0_reg_145.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c_0_reg_145.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_mult::thread_icmp_ln26_fu_183_p2() {
    icmp_ln26_fu_183_p2 = (!r_0_reg_134.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(r_0_reg_134.read() == ap_const_lv2_2);
}

void matrix_mult::thread_icmp_ln28_fu_199_p2() {
    icmp_ln28_fu_199_p2 = (!c_0_reg_145.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_145.read() == ap_const_lv2_2);
}

void matrix_mult::thread_icmp_ln31_fu_231_p2() {
    icmp_ln31_fu_231_p2 = (!p_0_reg_172.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(p_0_reg_172.read() == ap_const_lv2_2);
}

void matrix_mult::thread_mat_c_0_0() {
    mat_c_0_0 = sum_0_reg_156.read();
}

void matrix_mult::thread_mat_c_0_0_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_231_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(trunc_ln32_reg_289.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln32_1_reg_312.read()))) {
        mat_c_0_0_ap_vld = ap_const_logic_1;
    } else {
        mat_c_0_0_ap_vld = ap_const_logic_0;
    }
}

void matrix_mult::thread_mat_c_0_1() {
    mat_c_0_1 = sum_0_reg_156.read();
}

void matrix_mult::thread_mat_c_0_1_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_231_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(trunc_ln32_reg_289.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(trunc_ln32_1_reg_312.read(), ap_const_lv1_1))) {
        mat_c_0_1_ap_vld = ap_const_logic_1;
    } else {
        mat_c_0_1_ap_vld = ap_const_logic_0;
    }
}

void matrix_mult::thread_mat_c_1_0() {
    mat_c_1_0 = sum_0_reg_156.read();
}

void matrix_mult::thread_mat_c_1_0_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_231_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln32_1_reg_312.read()) && 
         esl_seteq<1,1,1>(trunc_ln32_reg_289.read(), ap_const_lv1_1))) {
        mat_c_1_0_ap_vld = ap_const_logic_1;
    } else {
        mat_c_1_0_ap_vld = ap_const_logic_0;
    }
}

void matrix_mult::thread_mat_c_1_1() {
    mat_c_1_1 = sum_0_reg_156.read();
}

void matrix_mult::thread_mat_c_1_1_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_231_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(trunc_ln32_1_reg_312.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(trunc_ln32_reg_289.read(), ap_const_lv1_1))) {
        mat_c_1_1_ap_vld = ap_const_logic_1;
    } else {
        mat_c_1_1_ap_vld = ap_const_logic_0;
    }
}

void matrix_mult::thread_mul_ln32_fu_272_p2() {
    mul_ln32_fu_272_p2 = (!select_ln32_4_reg_344.read().is_01() || !select_ln32_5_reg_349.read().is_01())? sc_lv<32>(): sc_bigint<32>(select_ln32_4_reg_344.read()) * sc_bigint<32>(select_ln32_5_reg_349.read());
}

void matrix_mult::thread_p_fu_237_p2() {
    p_fu_237_p2 = (!p_0_reg_172.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(p_0_reg_172.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_mult::thread_r_fu_189_p2() {
    r_fu_189_p2 = (!r_0_reg_134.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(r_0_reg_134.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_mult::thread_select_ln32_1_fu_253_p3() {
    select_ln32_1_fu_253_p3 = (!trunc_ln32_2_fu_243_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln32_2_fu_243_p1.read()[0].to_bool())? mat_a_0_1.read(): mat_a_0_0.read());
}

void matrix_mult::thread_select_ln32_2_fu_215_p3() {
    select_ln32_2_fu_215_p3 = (!trunc_ln32_1_fu_211_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln32_1_fu_211_p1.read()[0].to_bool())? mat_b_1_1.read(): mat_b_1_0.read());
}

void matrix_mult::thread_select_ln32_3_fu_223_p3() {
    select_ln32_3_fu_223_p3 = (!trunc_ln32_1_fu_211_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln32_1_fu_211_p1.read()[0].to_bool())? mat_b_0_1.read(): mat_b_0_0.read());
}

void matrix_mult::thread_select_ln32_4_fu_259_p3() {
    select_ln32_4_fu_259_p3 = (!trunc_ln32_reg_289.read()[0].is_01())? sc_lv<32>(): ((trunc_ln32_reg_289.read()[0].to_bool())? select_ln32_fu_247_p3.read(): select_ln32_1_fu_253_p3.read());
}

void matrix_mult::thread_select_ln32_5_fu_266_p3() {
    select_ln32_5_fu_266_p3 = (!trunc_ln32_2_fu_243_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln32_2_fu_243_p1.read()[0].to_bool())? select_ln32_2_reg_326.read(): select_ln32_3_reg_331.read());
}

void matrix_mult::thread_select_ln32_fu_247_p3() {
    select_ln32_fu_247_p3 = (!trunc_ln32_2_fu_243_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln32_2_fu_243_p1.read()[0].to_bool())? mat_a_1_1.read(): mat_a_1_0.read());
}

void matrix_mult::thread_sum_fu_276_p2() {
    sum_fu_276_p2 = (!mul_ln32_reg_354.read().is_01() || !sum_0_reg_156.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln32_reg_354.read()) + sc_biguint<32>(sum_0_reg_156.read()));
}

void matrix_mult::thread_trunc_ln32_1_fu_211_p1() {
    trunc_ln32_1_fu_211_p1 = c_0_reg_145.read().range(1-1, 0);
}

void matrix_mult::thread_trunc_ln32_2_fu_243_p1() {
    trunc_ln32_2_fu_243_p1 = p_0_reg_172.read().range(1-1, 0);
}

void matrix_mult::thread_trunc_ln32_fu_195_p1() {
    trunc_ln32_fu_195_p1 = r_0_reg_134.read().range(1-1, 0);
}

void matrix_mult::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln26_fu_183_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln28_fu_199_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln31_fu_231_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}

void matrix_mult::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mat_a_0_0\" :  \"" << mat_a_0_0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mat_a_0_1\" :  \"" << mat_a_0_1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mat_a_1_0\" :  \"" << mat_a_1_0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mat_a_1_1\" :  \"" << mat_a_1_1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mat_b_0_0\" :  \"" << mat_b_0_0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mat_b_0_1\" :  \"" << mat_b_0_1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mat_b_1_0\" :  \"" << mat_b_1_0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mat_b_1_1\" :  \"" << mat_b_1_1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mat_c_0_0\" :  \"" << mat_c_0_0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mat_c_0_0_ap_vld\" :  \"" << mat_c_0_0_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mat_c_0_1\" :  \"" << mat_c_0_1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mat_c_0_1_ap_vld\" :  \"" << mat_c_0_1_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mat_c_1_0\" :  \"" << mat_c_1_0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mat_c_1_0_ap_vld\" :  \"" << mat_c_1_0_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mat_c_1_1\" :  \"" << mat_c_1_1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mat_c_1_1_ap_vld\" :  \"" << mat_c_1_1_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

