// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sobel_rgb_axis,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.437000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=6,HLS_SYN_FF=1216,HLS_SYN_LUT=1496,HLS_VERSION=2019_2}" *)

module sobel_rgb_axis (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_axis_TDATA,
        in_axis_TVALID,
        in_axis_TREADY,
        in_axis_TKEEP,
        in_axis_TSTRB,
        in_axis_TUSER,
        in_axis_TLAST,
        in_axis_TID,
        in_axis_TDEST,
        out_axis_TDATA,
        out_axis_TVALID,
        out_axis_TREADY,
        out_axis_TKEEP,
        out_axis_TSTRB,
        out_axis_TUSER,
        out_axis_TLAST,
        out_axis_TID,
        out_axis_TDEST,
        width,
        height
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state10 = 4'd8;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] in_axis_TDATA;
input   in_axis_TVALID;
output   in_axis_TREADY;
input  [2:0] in_axis_TKEEP;
input  [2:0] in_axis_TSTRB;
input  [0:0] in_axis_TUSER;
input  [0:0] in_axis_TLAST;
input  [0:0] in_axis_TID;
input  [0:0] in_axis_TDEST;
output  [23:0] out_axis_TDATA;
output   out_axis_TVALID;
input   out_axis_TREADY;
output  [2:0] out_axis_TKEEP;
output  [2:0] out_axis_TSTRB;
output  [0:0] out_axis_TUSER;
output  [0:0] out_axis_TLAST;
output  [0:0] out_axis_TID;
output  [0:0] out_axis_TDEST;
input  [31:0] width;
input  [31:0] height;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_axis_TREADY;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] line0_V_address0;
reg    line0_V_ce0;
reg    line0_V_we0;
reg   [7:0] line0_V_d0;
wire   [7:0] line0_V_q0;
reg   [9:0] line1_V_address0;
reg    line1_V_ce0;
reg    line1_V_we0;
reg   [7:0] line1_V_d0;
wire   [7:0] line1_V_q0;
reg    in_axis_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln46_fu_391_p2;
reg    out_axis_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] icmp_ln46_reg_965;
reg   [0:0] icmp_ln46_reg_965_pp0_iter4_reg;
reg    ap_enable_reg_pp0_iter6;
reg   [0:0] icmp_ln46_reg_965_pp0_iter5_reg;
reg   [63:0] indvar_flatten_reg_239;
reg   [30:0] y_0_reg_250;
reg   [7:0] w2_1_V_reg_261;
reg   [7:0] w2_V_1_0_reg_273;
reg   [7:0] w1_1_V_reg_285;
reg   [7:0] w1_V_1_0_reg_297;
reg   [7:0] w0_1_V_reg_309;
reg   [7:0] w0_V_1_0_reg_321;
reg   [30:0] x1_0_reg_333;
wire   [0:0] icmp_ln39_fu_348_p2;
wire    ap_CS_fsm_state2;
wire   [30:0] x_fu_353_p2;
wire   [31:0] add_ln102_fu_365_p2;
reg   [31:0] add_ln102_reg_945;
wire   [63:0] mul_ln102_fu_376_p2;
reg   [63:0] mul_ln102_reg_950;
wire   [0:0] icmp_ln53_fu_386_p2;
reg   [0:0] icmp_ln53_reg_955;
reg    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
wire    ap_block_state8_pp0_stage0_iter5;
reg    ap_block_state8_io;
wire    ap_block_state9_pp0_stage0_iter6;
reg    ap_block_state9_io;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln53_reg_955_pp0_iter1_reg;
reg   [0:0] icmp_ln53_reg_955_pp0_iter2_reg;
reg   [0:0] icmp_ln46_reg_965_pp0_iter1_reg;
reg   [0:0] icmp_ln46_reg_965_pp0_iter2_reg;
reg   [0:0] icmp_ln46_reg_965_pp0_iter3_reg;
wire   [63:0] add_ln46_fu_396_p2;
wire   [30:0] select_ln46_7_fu_460_p3;
reg   [30:0] select_ln46_7_reg_974;
reg   [2:0] tmp_keep_V_reg_979;
reg   [2:0] tmp_keep_V_reg_979_pp0_iter1_reg;
reg   [2:0] tmp_keep_V_reg_979_pp0_iter2_reg;
reg   [2:0] tmp_keep_V_reg_979_pp0_iter3_reg;
reg   [2:0] tmp_keep_V_reg_979_pp0_iter4_reg;
reg   [2:0] tmp_strb_V_reg_984;
reg   [2:0] tmp_strb_V_reg_984_pp0_iter1_reg;
reg   [2:0] tmp_strb_V_reg_984_pp0_iter2_reg;
reg   [2:0] tmp_strb_V_reg_984_pp0_iter3_reg;
reg   [2:0] tmp_strb_V_reg_984_pp0_iter4_reg;
reg   [0:0] tmp_id_V_reg_989;
reg   [0:0] tmp_id_V_reg_989_pp0_iter1_reg;
reg   [0:0] tmp_id_V_reg_989_pp0_iter2_reg;
reg   [0:0] tmp_id_V_reg_989_pp0_iter3_reg;
reg   [0:0] tmp_id_V_reg_989_pp0_iter4_reg;
reg   [0:0] tmp_dest_V_reg_994;
reg   [0:0] tmp_dest_V_reg_994_pp0_iter1_reg;
reg   [0:0] tmp_dest_V_reg_994_pp0_iter2_reg;
reg   [0:0] tmp_dest_V_reg_994_pp0_iter3_reg;
reg   [0:0] tmp_dest_V_reg_994_pp0_iter4_reg;
wire   [7:0] b_V_fu_508_p1;
reg   [7:0] b_V_reg_999;
wire   [15:0] grp_fu_907_p3;
reg   [15:0] ret_V_1_reg_1004;
reg   [9:0] line1_V_addr_1_reg_1009;
reg   [9:0] line1_V_addr_1_reg_1009_pp0_iter1_reg;
reg   [9:0] line0_V_addr_1_reg_1014;
wire   [0:0] and_ln82_fu_548_p2;
reg   [0:0] and_ln82_reg_1019;
reg   [0:0] and_ln82_reg_1019_pp0_iter1_reg;
reg   [0:0] and_ln82_reg_1019_pp0_iter2_reg;
reg   [0:0] and_ln82_reg_1019_pp0_iter3_reg;
reg   [0:0] and_ln82_reg_1019_pp0_iter4_reg;
wire   [0:0] dout_user_V_fu_560_p2;
reg   [0:0] dout_user_V_reg_1026;
reg   [0:0] dout_user_V_reg_1026_pp0_iter1_reg;
reg   [0:0] dout_user_V_reg_1026_pp0_iter2_reg;
reg   [0:0] dout_user_V_reg_1026_pp0_iter3_reg;
reg   [0:0] dout_user_V_reg_1026_pp0_iter4_reg;
wire   [0:0] dout_last_V_fu_566_p2;
reg   [0:0] dout_last_V_reg_1031;
reg   [0:0] dout_last_V_reg_1031_pp0_iter1_reg;
reg   [0:0] dout_last_V_reg_1031_pp0_iter2_reg;
reg   [0:0] dout_last_V_reg_1031_pp0_iter3_reg;
reg   [0:0] dout_last_V_reg_1031_pp0_iter4_reg;
wire   [30:0] x_1_fu_571_p2;
reg   [7:0] gray_V_reg_1041;
reg    ap_enable_reg_pp0_iter1;
reg   [7:0] gray_V_reg_1041_pp0_iter2_reg;
reg   [7:0] gray_V_reg_1041_pp0_iter3_reg;
wire   [7:0] select_ln46_2_fu_590_p3;
reg   [7:0] select_ln46_2_reg_1048;
reg    ap_enable_reg_pp0_iter2;
reg   [7:0] top1_V_reg_1053;
wire   [7:0] select_ln46_8_fu_597_p3;
reg   [7:0] select_ln46_8_reg_1059;
reg   [7:0] select_ln46_8_reg_1059_pp0_iter3_reg;
wire   [7:0] select_ln46_fu_604_p3;
reg   [7:0] select_ln46_reg_1064;
reg    ap_enable_reg_pp0_iter3;
wire   [7:0] select_ln46_1_fu_611_p3;
reg   [7:0] select_ln46_1_reg_1070;
wire   [7:0] select_ln46_3_fu_618_p3;
reg   [7:0] select_ln46_3_reg_1075;
wire   [7:0] select_ln46_4_fu_625_p3;
reg   [7:0] select_ln46_4_reg_1081;
reg   [7:0] top2_V_reg_1087;
wire   [9:0] add_ln84_fu_647_p2;
reg   [9:0] add_ln84_reg_1093;
wire   [10:0] gx_fu_703_p2;
reg   [10:0] gx_reg_1098;
wire   [10:0] gy_fu_767_p2;
reg   [10:0] gy_reg_1103;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter4;
reg   [30:0] x_0_reg_228;
reg   [30:0] ap_phi_mux_y_0_phi_fu_254_p4;
reg   [7:0] ap_phi_mux_w2_1_V_phi_fu_265_p4;
reg   [7:0] ap_phi_mux_w2_V_1_0_phi_fu_277_p4;
reg   [7:0] ap_phi_mux_w1_1_V_phi_fu_289_p4;
reg   [7:0] ap_phi_mux_w1_V_1_0_phi_fu_301_p4;
reg   [7:0] ap_phi_mux_w0_1_V_phi_fu_313_p4;
reg   [7:0] ap_phi_mux_w0_V_1_0_phi_fu_325_p4;
wire   [63:0] zext_ln41_fu_359_p1;
wire   [63:0] zext_ln63_fu_526_p1;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] zext_ln39_fu_344_p1;
wire   [31:0] mul_ln102_fu_376_p0;
wire   [31:0] mul_ln102_fu_376_p1;
wire   [31:0] zext_ln53_fu_382_p1;
wire   [30:0] add_ln46_1_fu_410_p2;
wire   [29:0] tmp_fu_416_p4;
wire   [29:0] tmp_2_fu_432_p4;
wire   [0:0] icmp_ln82_1_fu_442_p2;
wire   [0:0] icmp_ln82_fu_426_p2;
wire   [30:0] select_ln46_5_fu_402_p3;
wire   [7:0] r_V_fu_488_p4;
wire   [7:0] g_V_fu_498_p4;
wire   [7:0] mul_ln215_fu_520_p1;
wire   [29:0] tmp_3_fu_532_p4;
wire   [0:0] select_ln46_6_fu_448_p3;
wire   [0:0] icmp_ln82_2_fu_542_p2;
wire   [30:0] or_ln101_fu_554_p2;
wire   [31:0] zext_ln46_fu_456_p1;
wire   [15:0] grp_fu_915_p3;
wire   [8:0] shl_ln85_1_fu_636_p3;
wire   [9:0] zext_ln85_3_fu_643_p1;
wire   [9:0] zext_ln85_1_fu_632_p1;
wire   [8:0] shl_ln_fu_662_p3;
wire   [10:0] zext_ln84_4_fu_682_p1;
wire   [10:0] zext_ln84_1_fu_656_p1;
wire   [10:0] sub_ln85_fu_685_p2;
wire   [10:0] zext_ln85_2_fu_669_p1;
wire   [10:0] sub_ln85_1_fu_691_p2;
wire   [10:0] zext_ln86_fu_673_p1;
wire   [10:0] sub_ln86_fu_697_p2;
wire   [10:0] zext_ln84_3_fu_679_p1;
wire   [8:0] shl_ln1_fu_709_p3;
wire   [8:0] shl_ln2_fu_720_p3;
wire   [8:0] zext_ln84_fu_653_p1;
wire   [8:0] zext_ln85_fu_659_p1;
wire   [8:0] add_ln88_fu_731_p2;
wire   [9:0] zext_ln88_1_fu_737_p1;
wire   [9:0] zext_ln88_fu_716_p1;
wire   [9:0] add_ln88_1_fu_741_p2;
wire   [10:0] zext_ln88_2_fu_747_p1;
wire   [9:0] zext_ln89_fu_727_p1;
wire   [9:0] zext_ln84_2_fu_676_p1;
wire   [9:0] add_ln89_fu_757_p2;
wire   [10:0] zext_ln89_1_fu_763_p1;
wire   [10:0] sub_ln89_fu_751_p2;
wire   [10:0] select_ln82_fu_773_p3;
wire   [10:0] select_ln82_1_fu_783_p3;
wire   [9:0] trunc_ln82_fu_779_p1;
wire   [0:0] tmp_4_fu_793_p3;
wire   [9:0] sub_ln91_fu_801_p2;
wire   [9:0] select_ln91_fu_807_p3;
wire   [9:0] trunc_ln82_1_fu_789_p1;
wire   [0:0] tmp_5_fu_819_p3;
wire   [9:0] sub_ln91_1_fu_827_p2;
wire   [9:0] select_ln91_1_fu_833_p3;
wire   [10:0] zext_ln91_1_fu_841_p1;
wire   [10:0] zext_ln91_fu_815_p1;
wire   [10:0] mag_fu_853_p2;
wire   [2:0] tmp_6_fu_859_p4;
wire   [7:0] trunc_ln91_fu_845_p1;
wire   [7:0] trunc_ln91_1_fu_849_p1;
wire   [0:0] icmp_ln92_fu_869_p2;
wire   [7:0] add_ln301_fu_875_p2;
wire   [7:0] edge_V_fu_881_p3;
wire   [7:0] edge_V_1_fu_889_p3;
wire   [7:0] grp_fu_907_p0;
wire   [7:0] grp_fu_907_p1;
wire   [15:0] grp_fu_907_p2;
wire   [5:0] grp_fu_915_p0;
wire   [7:0] grp_fu_915_p1;
wire    ap_CS_fsm_state10;
wire    regslice_both_out_axis_V_data_V_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_in_axis_V_data_V_U_apdone_blk;
wire   [23:0] in_axis_TDATA_int;
wire    in_axis_TVALID_int;
reg    in_axis_TREADY_int;
wire    regslice_both_in_axis_V_data_V_U_ack_in;
wire    regslice_both_in_axis_V_keep_V_U_apdone_blk;
wire   [2:0] in_axis_TKEEP_int;
wire    regslice_both_in_axis_V_keep_V_U_vld_out;
wire    regslice_both_in_axis_V_keep_V_U_ack_in;
wire    regslice_both_in_axis_V_strb_V_U_apdone_blk;
wire   [2:0] in_axis_TSTRB_int;
wire    regslice_both_in_axis_V_strb_V_U_vld_out;
wire    regslice_both_in_axis_V_strb_V_U_ack_in;
wire    regslice_both_in_axis_V_user_V_U_apdone_blk;
wire   [0:0] in_axis_TUSER_int;
wire    regslice_both_in_axis_V_user_V_U_vld_out;
wire    regslice_both_in_axis_V_user_V_U_ack_in;
wire    regslice_both_in_axis_V_last_V_U_apdone_blk;
wire   [0:0] in_axis_TLAST_int;
wire    regslice_both_in_axis_V_last_V_U_vld_out;
wire    regslice_both_in_axis_V_last_V_U_ack_in;
wire    regslice_both_in_axis_V_id_V_U_apdone_blk;
wire   [0:0] in_axis_TID_int;
wire    regslice_both_in_axis_V_id_V_U_vld_out;
wire    regslice_both_in_axis_V_id_V_U_ack_in;
wire    regslice_both_in_axis_V_dest_V_U_apdone_blk;
wire   [0:0] in_axis_TDEST_int;
wire    regslice_both_in_axis_V_dest_V_U_vld_out;
wire    regslice_both_in_axis_V_dest_V_U_ack_in;
wire   [23:0] out_axis_TDATA_int;
reg    out_axis_TVALID_int;
wire    out_axis_TREADY_int;
wire    regslice_both_out_axis_V_data_V_U_vld_out;
wire    regslice_both_out_axis_V_keep_V_U_apdone_blk;
wire    regslice_both_out_axis_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_axis_V_keep_V_U_vld_out;
wire    regslice_both_out_axis_V_strb_V_U_apdone_blk;
wire    regslice_both_out_axis_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_axis_V_strb_V_U_vld_out;
wire    regslice_both_out_axis_V_user_V_U_apdone_blk;
wire    regslice_both_out_axis_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_axis_V_user_V_U_vld_out;
wire    regslice_both_out_axis_V_last_V_U_apdone_blk;
wire    regslice_both_out_axis_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_axis_V_last_V_U_vld_out;
wire    regslice_both_out_axis_V_id_V_U_apdone_blk;
wire    regslice_both_out_axis_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_axis_V_id_V_U_vld_out;
wire    regslice_both_out_axis_V_dest_V_U_apdone_blk;
wire    regslice_both_out_axis_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_axis_V_dest_V_U_vld_out;
wire   [15:0] grp_fu_907_p10;
wire   [13:0] grp_fu_915_p10;
wire   [63:0] mul_ln102_fu_376_p00;
wire   [63:0] mul_ln102_fu_376_p10;
wire   [15:0] mul_ln215_fu_520_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

sobel_rgb_axis_libkb #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
line0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line0_V_address0),
    .ce0(line0_V_ce0),
    .we0(line0_V_we0),
    .d0(line0_V_d0),
    .q0(line0_V_q0)
);

sobel_rgb_axis_libkb #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
line1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line1_V_address0),
    .ce0(line1_V_ce0),
    .we0(line1_V_we0),
    .d0(line1_V_d0),
    .q0(line1_V_q0)
);

sobel_rgb_axis_madEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
sobel_rgb_axis_madEe_U1(
    .din0(grp_fu_907_p0),
    .din1(grp_fu_907_p1),
    .din2(grp_fu_907_p2),
    .dout(grp_fu_907_p3)
);

sobel_rgb_axis_maeOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
sobel_rgb_axis_maeOg_U2(
    .din0(grp_fu_915_p0),
    .din1(grp_fu_915_p1),
    .din2(ret_V_1_reg_1004),
    .dout(grp_fu_915_p3)
);

regslice_both #(
    .DataWidth( 24 ))
regslice_both_in_axis_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_axis_TDATA),
    .vld_in(in_axis_TVALID),
    .ack_in(regslice_both_in_axis_V_data_V_U_ack_in),
    .data_out(in_axis_TDATA_int),
    .vld_out(in_axis_TVALID_int),
    .ack_out(in_axis_TREADY_int),
    .apdone_blk(regslice_both_in_axis_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 3 ))
regslice_both_in_axis_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_axis_TKEEP),
    .vld_in(in_axis_TVALID),
    .ack_in(regslice_both_in_axis_V_keep_V_U_ack_in),
    .data_out(in_axis_TKEEP_int),
    .vld_out(regslice_both_in_axis_V_keep_V_U_vld_out),
    .ack_out(in_axis_TREADY_int),
    .apdone_blk(regslice_both_in_axis_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 3 ))
regslice_both_in_axis_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_axis_TSTRB),
    .vld_in(in_axis_TVALID),
    .ack_in(regslice_both_in_axis_V_strb_V_U_ack_in),
    .data_out(in_axis_TSTRB_int),
    .vld_out(regslice_both_in_axis_V_strb_V_U_vld_out),
    .ack_out(in_axis_TREADY_int),
    .apdone_blk(regslice_both_in_axis_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_axis_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_axis_TUSER),
    .vld_in(in_axis_TVALID),
    .ack_in(regslice_both_in_axis_V_user_V_U_ack_in),
    .data_out(in_axis_TUSER_int),
    .vld_out(regslice_both_in_axis_V_user_V_U_vld_out),
    .ack_out(in_axis_TREADY_int),
    .apdone_blk(regslice_both_in_axis_V_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_axis_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_axis_TLAST),
    .vld_in(in_axis_TVALID),
    .ack_in(regslice_both_in_axis_V_last_V_U_ack_in),
    .data_out(in_axis_TLAST_int),
    .vld_out(regslice_both_in_axis_V_last_V_U_vld_out),
    .ack_out(in_axis_TREADY_int),
    .apdone_blk(regslice_both_in_axis_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_axis_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_axis_TID),
    .vld_in(in_axis_TVALID),
    .ack_in(regslice_both_in_axis_V_id_V_U_ack_in),
    .data_out(in_axis_TID_int),
    .vld_out(regslice_both_in_axis_V_id_V_U_vld_out),
    .ack_out(in_axis_TREADY_int),
    .apdone_blk(regslice_both_in_axis_V_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_axis_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_axis_TDEST),
    .vld_in(in_axis_TVALID),
    .ack_in(regslice_both_in_axis_V_dest_V_U_ack_in),
    .data_out(in_axis_TDEST_int),
    .vld_out(regslice_both_in_axis_V_dest_V_U_vld_out),
    .ack_out(in_axis_TREADY_int),
    .apdone_blk(regslice_both_in_axis_V_dest_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 24 ))
regslice_both_out_axis_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_axis_TDATA_int),
    .vld_in(out_axis_TVALID_int),
    .ack_in(out_axis_TREADY_int),
    .data_out(out_axis_TDATA),
    .vld_out(regslice_both_out_axis_V_data_V_U_vld_out),
    .ack_out(out_axis_TREADY),
    .apdone_blk(regslice_both_out_axis_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 3 ))
regslice_both_out_axis_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_keep_V_reg_979_pp0_iter4_reg),
    .vld_in(out_axis_TVALID_int),
    .ack_in(regslice_both_out_axis_V_keep_V_U_ack_in_dummy),
    .data_out(out_axis_TKEEP),
    .vld_out(regslice_both_out_axis_V_keep_V_U_vld_out),
    .ack_out(out_axis_TREADY),
    .apdone_blk(regslice_both_out_axis_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 3 ))
regslice_both_out_axis_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_strb_V_reg_984_pp0_iter4_reg),
    .vld_in(out_axis_TVALID_int),
    .ack_in(regslice_both_out_axis_V_strb_V_U_ack_in_dummy),
    .data_out(out_axis_TSTRB),
    .vld_out(regslice_both_out_axis_V_strb_V_U_vld_out),
    .ack_out(out_axis_TREADY),
    .apdone_blk(regslice_both_out_axis_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_axis_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dout_user_V_reg_1026_pp0_iter4_reg),
    .vld_in(out_axis_TVALID_int),
    .ack_in(regslice_both_out_axis_V_user_V_U_ack_in_dummy),
    .data_out(out_axis_TUSER),
    .vld_out(regslice_both_out_axis_V_user_V_U_vld_out),
    .ack_out(out_axis_TREADY),
    .apdone_blk(regslice_both_out_axis_V_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_axis_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dout_last_V_reg_1031_pp0_iter4_reg),
    .vld_in(out_axis_TVALID_int),
    .ack_in(regslice_both_out_axis_V_last_V_U_ack_in_dummy),
    .data_out(out_axis_TLAST),
    .vld_out(regslice_both_out_axis_V_last_V_U_vld_out),
    .ack_out(out_axis_TREADY),
    .apdone_blk(regslice_both_out_axis_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_axis_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_id_V_reg_989_pp0_iter4_reg),
    .vld_in(out_axis_TVALID_int),
    .ack_in(regslice_both_out_axis_V_id_V_U_ack_in_dummy),
    .data_out(out_axis_TID),
    .vld_out(regslice_both_out_axis_V_id_V_U_vld_out),
    .ack_out(out_axis_TREADY),
    .apdone_blk(regslice_both_out_axis_V_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_axis_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_dest_V_reg_994_pp0_iter4_reg),
    .vld_in(out_axis_TVALID_int),
    .ack_in(regslice_both_out_axis_V_dest_V_U_ack_in_dummy),
    .data_out(out_axis_TDEST),
    .vld_out(regslice_both_out_axis_V_dest_V_U_vld_out),
    .ack_out(out_axis_TREADY),
    .apdone_blk(regslice_both_out_axis_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end else if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_391_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_239 <= add_ln46_fu_396_p2;
    end else if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_reg_239 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w0_1_V_reg_309 <= top2_V_reg_1087;
    end else if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        w0_1_V_reg_309 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w0_V_1_0_reg_321 <= select_ln46_3_reg_1075;
    end else if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        w0_V_1_0_reg_321 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w1_1_V_reg_285 <= top1_V_reg_1053;
    end else if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        w1_1_V_reg_285 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w1_V_1_0_reg_297 <= select_ln46_2_reg_1048;
    end else if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        w1_V_1_0_reg_297 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_1_V_reg_261 <= gray_V_reg_1041_pp0_iter3_reg;
    end else if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        w2_1_V_reg_261 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_V_1_0_reg_273 <= select_ln46_reg_1064;
    end else if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        w2_V_1_0_reg_273 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_391_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x1_0_reg_333 <= x_1_fu_571_p2;
    end else if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        x1_0_reg_333 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln39_fu_348_p2 == 1'd1))) begin
        x_0_reg_228 <= x_fu_353_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        x_0_reg_228 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        y_0_reg_250 <= select_ln46_7_reg_974;
    end else if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_0_reg_250 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln102_reg_945 <= add_ln102_fu_365_p2;
        mul_ln102_reg_950 <= mul_ln102_fu_376_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter2_reg == 1'd0) & (1'd1 == and_ln82_reg_1019_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln84_reg_1093 <= add_ln84_fu_647_p2;
        select_ln46_1_reg_1070 <= select_ln46_1_fu_611_p3;
        select_ln46_4_reg_1081 <= select_ln46_4_fu_625_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_391_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln82_reg_1019 <= and_ln82_fu_548_p2;
        b_V_reg_999 <= b_V_fu_508_p1;
        dout_last_V_reg_1031 <= dout_last_V_fu_566_p2;
        dout_user_V_reg_1026 <= dout_user_V_fu_560_p2;
        line0_V_addr_1_reg_1014 <= zext_ln63_fu_526_p1;
        line1_V_addr_1_reg_1009 <= zext_ln63_fu_526_p1;
        tmp_dest_V_reg_994 <= in_axis_TDEST_int;
        tmp_id_V_reg_989 <= in_axis_TID_int;
        tmp_keep_V_reg_979 <= in_axis_TKEEP_int;
        tmp_strb_V_reg_984 <= in_axis_TSTRB_int;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln82_reg_1019_pp0_iter1_reg <= and_ln82_reg_1019;
        dout_last_V_reg_1031_pp0_iter1_reg <= dout_last_V_reg_1031;
        dout_user_V_reg_1026_pp0_iter1_reg <= dout_user_V_reg_1026;
        icmp_ln46_reg_965 <= icmp_ln46_fu_391_p2;
        icmp_ln46_reg_965_pp0_iter1_reg <= icmp_ln46_reg_965;
        icmp_ln53_reg_955 <= icmp_ln53_fu_386_p2;
        icmp_ln53_reg_955_pp0_iter1_reg <= icmp_ln53_reg_955;
        line1_V_addr_1_reg_1009_pp0_iter1_reg <= line1_V_addr_1_reg_1009;
        tmp_dest_V_reg_994_pp0_iter1_reg <= tmp_dest_V_reg_994;
        tmp_id_V_reg_989_pp0_iter1_reg <= tmp_id_V_reg_989;
        tmp_keep_V_reg_979_pp0_iter1_reg <= tmp_keep_V_reg_979;
        tmp_strb_V_reg_984_pp0_iter1_reg <= tmp_strb_V_reg_984;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln82_reg_1019_pp0_iter2_reg <= and_ln82_reg_1019_pp0_iter1_reg;
        and_ln82_reg_1019_pp0_iter3_reg <= and_ln82_reg_1019_pp0_iter2_reg;
        and_ln82_reg_1019_pp0_iter4_reg <= and_ln82_reg_1019_pp0_iter3_reg;
        dout_last_V_reg_1031_pp0_iter2_reg <= dout_last_V_reg_1031_pp0_iter1_reg;
        dout_last_V_reg_1031_pp0_iter3_reg <= dout_last_V_reg_1031_pp0_iter2_reg;
        dout_last_V_reg_1031_pp0_iter4_reg <= dout_last_V_reg_1031_pp0_iter3_reg;
        dout_user_V_reg_1026_pp0_iter2_reg <= dout_user_V_reg_1026_pp0_iter1_reg;
        dout_user_V_reg_1026_pp0_iter3_reg <= dout_user_V_reg_1026_pp0_iter2_reg;
        dout_user_V_reg_1026_pp0_iter4_reg <= dout_user_V_reg_1026_pp0_iter3_reg;
        gray_V_reg_1041_pp0_iter2_reg <= gray_V_reg_1041;
        gray_V_reg_1041_pp0_iter3_reg <= gray_V_reg_1041_pp0_iter2_reg;
        icmp_ln46_reg_965_pp0_iter2_reg <= icmp_ln46_reg_965_pp0_iter1_reg;
        icmp_ln46_reg_965_pp0_iter3_reg <= icmp_ln46_reg_965_pp0_iter2_reg;
        icmp_ln46_reg_965_pp0_iter4_reg <= icmp_ln46_reg_965_pp0_iter3_reg;
        icmp_ln46_reg_965_pp0_iter5_reg <= icmp_ln46_reg_965_pp0_iter4_reg;
        icmp_ln53_reg_955_pp0_iter2_reg <= icmp_ln53_reg_955_pp0_iter1_reg;
        select_ln46_8_reg_1059_pp0_iter3_reg <= select_ln46_8_reg_1059;
        tmp_dest_V_reg_994_pp0_iter2_reg <= tmp_dest_V_reg_994_pp0_iter1_reg;
        tmp_dest_V_reg_994_pp0_iter3_reg <= tmp_dest_V_reg_994_pp0_iter2_reg;
        tmp_dest_V_reg_994_pp0_iter4_reg <= tmp_dest_V_reg_994_pp0_iter3_reg;
        tmp_id_V_reg_989_pp0_iter2_reg <= tmp_id_V_reg_989_pp0_iter1_reg;
        tmp_id_V_reg_989_pp0_iter3_reg <= tmp_id_V_reg_989_pp0_iter2_reg;
        tmp_id_V_reg_989_pp0_iter4_reg <= tmp_id_V_reg_989_pp0_iter3_reg;
        tmp_keep_V_reg_979_pp0_iter2_reg <= tmp_keep_V_reg_979_pp0_iter1_reg;
        tmp_keep_V_reg_979_pp0_iter3_reg <= tmp_keep_V_reg_979_pp0_iter2_reg;
        tmp_keep_V_reg_979_pp0_iter4_reg <= tmp_keep_V_reg_979_pp0_iter3_reg;
        tmp_strb_V_reg_984_pp0_iter2_reg <= tmp_strb_V_reg_984_pp0_iter1_reg;
        tmp_strb_V_reg_984_pp0_iter3_reg <= tmp_strb_V_reg_984_pp0_iter2_reg;
        tmp_strb_V_reg_984_pp0_iter4_reg <= tmp_strb_V_reg_984_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gray_V_reg_1041 <= {{grp_fu_915_p3[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter3_reg == 1'd0) & (1'd1 == and_ln82_reg_1019_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gx_reg_1098 <= gx_fu_703_p2;
        gy_reg_1103 <= gy_fu_767_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_391_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ret_V_1_reg_1004 <= grp_fu_907_p3;
        select_ln46_7_reg_974 <= select_ln46_7_fu_460_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln46_2_reg_1048 <= select_ln46_2_fu_590_p3;
        top1_V_reg_1053 <= line0_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln46_3_reg_1075 <= select_ln46_3_fu_618_p3;
        top2_V_reg_1087 <= line1_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter1_reg == 1'd0) & (1'd1 == and_ln82_reg_1019_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln46_8_reg_1059 <= select_ln46_8_fu_597_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_965_pp0_iter2_reg == 1'd0) & (1'd1 == and_ln82_reg_1019_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln46_reg_1064 <= select_ln46_fu_604_p3;
    end
end

always @ (*) begin
    if ((icmp_ln46_fu_391_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_axis_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_mux_w0_1_V_phi_fu_313_p4 = top2_V_reg_1087;
    end else begin
        ap_phi_mux_w0_1_V_phi_fu_313_p4 = w0_1_V_reg_309;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_mux_w0_V_1_0_phi_fu_325_p4 = select_ln46_3_reg_1075;
    end else begin
        ap_phi_mux_w0_V_1_0_phi_fu_325_p4 = w0_V_1_0_reg_321;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_mux_w1_1_V_phi_fu_289_p4 = top1_V_reg_1053;
    end else begin
        ap_phi_mux_w1_1_V_phi_fu_289_p4 = w1_1_V_reg_285;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_mux_w1_V_1_0_phi_fu_301_p4 = select_ln46_2_reg_1048;
    end else begin
        ap_phi_mux_w1_V_1_0_phi_fu_301_p4 = w1_V_1_0_reg_297;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_mux_w2_1_V_phi_fu_265_p4 = gray_V_reg_1041_pp0_iter3_reg;
    end else begin
        ap_phi_mux_w2_1_V_phi_fu_265_p4 = w2_1_V_reg_261;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_mux_w2_V_1_0_phi_fu_277_p4 = select_ln46_reg_1064;
    end else begin
        ap_phi_mux_w2_V_1_0_phi_fu_277_p4 = w2_V_1_0_reg_273;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_y_0_phi_fu_254_p4 = select_ln46_7_reg_974;
    end else begin
        ap_phi_mux_y_0_phi_fu_254_p4 = y_0_reg_250;
    end
end

always @ (*) begin
    if (((regslice_both_out_axis_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_391_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_axis_TDATA_blk_n = in_axis_TVALID_int;
    end else begin
        in_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((regslice_both_in_axis_V_data_V_U_ack_in == 1'b1) & (in_axis_TVALID == 1'b1))) begin
        in_axis_TREADY = 1'b1;
    end else begin
        in_axis_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_391_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_axis_TREADY_int = 1'b1;
    end else begin
        in_axis_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line0_V_address0 = line0_V_addr_1_reg_1014;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line0_V_address0 = zext_ln41_fu_359_p1;
    end else begin
        line0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln46_reg_965 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        line0_V_ce0 = 1'b1;
    end else begin
        line0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line0_V_d0 = {{grp_fu_915_p3[15:8]}};
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line0_V_d0 = 8'd0;
    end else begin
        line0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln46_reg_965 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln39_fu_348_p2 == 1'd1)))) begin
        line0_V_we0 = 1'b1;
    end else begin
        line0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        line1_V_address0 = line1_V_addr_1_reg_1009_pp0_iter1_reg;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line1_V_address0 = zext_ln41_fu_359_p1;
    end else begin
        line1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln46_reg_965_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        line1_V_ce0 = 1'b1;
    end else begin
        line1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        line1_V_d0 = line0_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line1_V_d0 = 8'd0;
    end else begin
        line1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln46_reg_965_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln39_fu_348_p2 == 1'd1)))) begin
        line1_V_we0 = 1'b1;
    end else begin
        line1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln46_reg_965_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((icmp_ln46_reg_965_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        out_axis_TDATA_blk_n = out_axis_TREADY_int;
    end else begin
        out_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_965_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_axis_TVALID_int = 1'b1;
    end else begin
        out_axis_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln39_fu_348_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln46_fu_391_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter5 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter5 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((icmp_ln46_fu_391_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((regslice_both_out_axis_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln102_fu_365_p2 = ($signed(width) + $signed(32'd4294967295));

assign add_ln301_fu_875_p2 = (trunc_ln91_fu_845_p1 + trunc_ln91_1_fu_849_p1);

assign add_ln46_1_fu_410_p2 = (31'd1 + ap_phi_mux_y_0_phi_fu_254_p4);

assign add_ln46_fu_396_p2 = (indvar_flatten_reg_239 + 64'd1);

assign add_ln84_fu_647_p2 = (zext_ln85_3_fu_643_p1 + zext_ln85_1_fu_632_p1);

assign add_ln88_1_fu_741_p2 = (zext_ln88_1_fu_737_p1 + zext_ln88_fu_716_p1);

assign add_ln88_fu_731_p2 = (zext_ln84_fu_653_p1 + zext_ln85_fu_659_p1);

assign add_ln89_fu_757_p2 = (zext_ln89_fu_727_p1 + zext_ln84_2_fu_676_p1);

assign and_ln82_fu_548_p2 = (select_ln46_6_fu_448_p3 & icmp_ln82_2_fu_542_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((icmp_ln46_fu_391_p2 == 1'd0) & (in_axis_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state9_io) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((icmp_ln46_fu_391_p2 == 1'd0) & (in_axis_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state9_io) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((icmp_ln46_fu_391_p2 == 1'd0) & (in_axis_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter0 = ((icmp_ln46_fu_391_p2 == 1'd0) & (in_axis_TVALID_int == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((icmp_ln46_reg_965_pp0_iter4_reg == 1'd0) & (out_axis_TREADY_int == 1'b0));
end

assign ap_block_state8_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_io = ((icmp_ln46_reg_965_pp0_iter5_reg == 1'd0) & (out_axis_TREADY_int == 1'b0));
end

assign ap_block_state9_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign b_V_fu_508_p1 = in_axis_TDATA_int[7:0];

assign dout_last_V_fu_566_p2 = ((zext_ln46_fu_456_p1 == add_ln102_reg_945) ? 1'b1 : 1'b0);

assign dout_user_V_fu_560_p2 = ((or_ln101_fu_554_p2 == 31'd0) ? 1'b1 : 1'b0);

assign edge_V_1_fu_889_p3 = ((and_ln82_reg_1019_pp0_iter4_reg[0:0] === 1'b1) ? edge_V_fu_881_p3 : 8'd0);

assign edge_V_fu_881_p3 = ((icmp_ln92_fu_869_p2[0:0] === 1'b1) ? 8'd255 : add_ln301_fu_875_p2);

assign g_V_fu_498_p4 = {{in_axis_TDATA_int[15:8]}};

assign grp_fu_907_p0 = 16'd77;

assign grp_fu_907_p1 = grp_fu_907_p10;

assign grp_fu_907_p10 = r_V_fu_488_p4;

assign grp_fu_907_p2 = (16'd150 * mul_ln215_fu_520_p1);

assign grp_fu_915_p0 = 14'd29;

assign grp_fu_915_p1 = grp_fu_915_p10;

assign grp_fu_915_p10 = b_V_reg_999;

assign gx_fu_703_p2 = (sub_ln86_fu_697_p2 + zext_ln84_3_fu_679_p1);

assign gy_fu_767_p2 = (zext_ln89_1_fu_763_p1 + sub_ln89_fu_751_p2);

assign icmp_ln39_fu_348_p2 = (($signed(zext_ln39_fu_344_p1) < $signed(width)) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_391_p2 = ((indvar_flatten_reg_239 == mul_ln102_reg_950) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_386_p2 = (($signed(zext_ln53_fu_382_p1) < $signed(width)) ? 1'b1 : 1'b0);

assign icmp_ln82_1_fu_442_p2 = ((tmp_2_fu_432_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln82_2_fu_542_p2 = ((tmp_3_fu_532_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_426_p2 = ((tmp_fu_416_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_869_p2 = ((tmp_6_fu_859_p4 != 3'd0) ? 1'b1 : 1'b0);

assign mag_fu_853_p2 = (zext_ln91_1_fu_841_p1 + zext_ln91_fu_815_p1);

assign mul_ln102_fu_376_p0 = mul_ln102_fu_376_p00;

assign mul_ln102_fu_376_p00 = width;

assign mul_ln102_fu_376_p1 = mul_ln102_fu_376_p10;

assign mul_ln102_fu_376_p10 = height;

assign mul_ln102_fu_376_p2 = (mul_ln102_fu_376_p0 * mul_ln102_fu_376_p1);

assign mul_ln215_fu_520_p1 = mul_ln215_fu_520_p10;

assign mul_ln215_fu_520_p10 = g_V_fu_498_p4;

assign or_ln101_fu_554_p2 = (select_ln46_7_fu_460_p3 | select_ln46_5_fu_402_p3);

assign out_axis_TDATA_int = {{{edge_V_1_fu_889_p3}, {edge_V_1_fu_889_p3}}, {edge_V_1_fu_889_p3}};

assign out_axis_TVALID = regslice_both_out_axis_V_data_V_U_vld_out;

assign r_V_fu_488_p4 = {{in_axis_TDATA_int[23:16]}};

assign select_ln46_1_fu_611_p3 = ((icmp_ln53_reg_955_pp0_iter2_reg[0:0] === 1'b1) ? ap_phi_mux_w2_V_1_0_phi_fu_277_p4 : 8'd0);

assign select_ln46_2_fu_590_p3 = ((icmp_ln53_reg_955_pp0_iter1_reg[0:0] === 1'b1) ? ap_phi_mux_w1_1_V_phi_fu_289_p4 : 8'd0);

assign select_ln46_3_fu_618_p3 = ((icmp_ln53_reg_955_pp0_iter2_reg[0:0] === 1'b1) ? ap_phi_mux_w0_1_V_phi_fu_313_p4 : 8'd0);

assign select_ln46_4_fu_625_p3 = ((icmp_ln53_reg_955_pp0_iter2_reg[0:0] === 1'b1) ? ap_phi_mux_w0_V_1_0_phi_fu_325_p4 : 8'd0);

assign select_ln46_5_fu_402_p3 = ((icmp_ln53_fu_386_p2[0:0] === 1'b1) ? x1_0_reg_333 : 31'd0);

assign select_ln46_6_fu_448_p3 = ((icmp_ln53_fu_386_p2[0:0] === 1'b1) ? icmp_ln82_1_fu_442_p2 : icmp_ln82_fu_426_p2);

assign select_ln46_7_fu_460_p3 = ((icmp_ln53_fu_386_p2[0:0] === 1'b1) ? ap_phi_mux_y_0_phi_fu_254_p4 : add_ln46_1_fu_410_p2);

assign select_ln46_8_fu_597_p3 = ((icmp_ln53_reg_955_pp0_iter1_reg[0:0] === 1'b1) ? ap_phi_mux_w1_V_1_0_phi_fu_301_p4 : 8'd0);

assign select_ln46_fu_604_p3 = ((icmp_ln53_reg_955_pp0_iter2_reg[0:0] === 1'b1) ? ap_phi_mux_w2_1_V_phi_fu_265_p4 : 8'd0);

assign select_ln82_1_fu_783_p3 = ((and_ln82_reg_1019_pp0_iter4_reg[0:0] === 1'b1) ? gy_reg_1103 : 11'd0);

assign select_ln82_fu_773_p3 = ((and_ln82_reg_1019_pp0_iter4_reg[0:0] === 1'b1) ? gx_reg_1098 : 11'd0);

assign select_ln91_1_fu_833_p3 = ((tmp_5_fu_819_p3[0:0] === 1'b1) ? sub_ln91_1_fu_827_p2 : trunc_ln82_1_fu_789_p1);

assign select_ln91_fu_807_p3 = ((tmp_4_fu_793_p3[0:0] === 1'b1) ? sub_ln91_fu_801_p2 : trunc_ln82_fu_779_p1);

assign shl_ln1_fu_709_p3 = {{select_ln46_3_reg_1075}, {1'd0}};

assign shl_ln2_fu_720_p3 = {{select_ln46_reg_1064}, {1'd0}};

assign shl_ln85_1_fu_636_p3 = {{top1_V_reg_1053}, {1'd0}};

assign shl_ln_fu_662_p3 = {{select_ln46_8_reg_1059_pp0_iter3_reg}, {1'd0}};

assign sub_ln85_1_fu_691_p2 = (sub_ln85_fu_685_p2 - zext_ln85_2_fu_669_p1);

assign sub_ln85_fu_685_p2 = (zext_ln84_4_fu_682_p1 - zext_ln84_1_fu_656_p1);

assign sub_ln86_fu_697_p2 = (sub_ln85_1_fu_691_p2 - zext_ln86_fu_673_p1);

assign sub_ln89_fu_751_p2 = (zext_ln86_fu_673_p1 - zext_ln88_2_fu_747_p1);

assign sub_ln91_1_fu_827_p2 = (10'd0 - trunc_ln82_1_fu_789_p1);

assign sub_ln91_fu_801_p2 = (10'd0 - trunc_ln82_fu_779_p1);

assign tmp_2_fu_432_p4 = {{ap_phi_mux_y_0_phi_fu_254_p4[30:1]}};

assign tmp_3_fu_532_p4 = {{select_ln46_5_fu_402_p3[30:1]}};

assign tmp_4_fu_793_p3 = select_ln82_fu_773_p3[32'd10];

assign tmp_5_fu_819_p3 = select_ln82_1_fu_783_p3[32'd10];

assign tmp_6_fu_859_p4 = {{mag_fu_853_p2[10:8]}};

assign tmp_fu_416_p4 = {{add_ln46_1_fu_410_p2[30:1]}};

assign trunc_ln82_1_fu_789_p1 = select_ln82_1_fu_783_p3[9:0];

assign trunc_ln82_fu_779_p1 = select_ln82_fu_773_p3[9:0];

assign trunc_ln91_1_fu_849_p1 = select_ln91_1_fu_833_p3[7:0];

assign trunc_ln91_fu_845_p1 = select_ln91_fu_807_p3[7:0];

assign x_1_fu_571_p2 = (31'd1 + select_ln46_5_fu_402_p3);

assign x_fu_353_p2 = (x_0_reg_228 + 31'd1);

assign zext_ln39_fu_344_p1 = x_0_reg_228;

assign zext_ln41_fu_359_p1 = x_0_reg_228;

assign zext_ln46_fu_456_p1 = select_ln46_5_fu_402_p3;

assign zext_ln53_fu_382_p1 = x1_0_reg_333;

assign zext_ln63_fu_526_p1 = select_ln46_5_fu_402_p3;

assign zext_ln84_1_fu_656_p1 = select_ln46_4_reg_1081;

assign zext_ln84_2_fu_676_p1 = gray_V_reg_1041_pp0_iter3_reg;

assign zext_ln84_3_fu_679_p1 = gray_V_reg_1041_pp0_iter3_reg;

assign zext_ln84_4_fu_682_p1 = add_ln84_reg_1093;

assign zext_ln84_fu_653_p1 = select_ln46_4_reg_1081;

assign zext_ln85_1_fu_632_p1 = line1_V_q0;

assign zext_ln85_2_fu_669_p1 = shl_ln_fu_662_p3;

assign zext_ln85_3_fu_643_p1 = shl_ln85_1_fu_636_p3;

assign zext_ln85_fu_659_p1 = top2_V_reg_1087;

assign zext_ln86_fu_673_p1 = select_ln46_1_reg_1070;

assign zext_ln88_1_fu_737_p1 = add_ln88_fu_731_p2;

assign zext_ln88_2_fu_747_p1 = add_ln88_1_fu_741_p2;

assign zext_ln88_fu_716_p1 = shl_ln1_fu_709_p3;

assign zext_ln89_1_fu_763_p1 = add_ln89_fu_757_p2;

assign zext_ln89_fu_727_p1 = shl_ln2_fu_720_p3;

assign zext_ln91_1_fu_841_p1 = select_ln91_1_fu_833_p3;

assign zext_ln91_fu_815_p1 = select_ln91_fu_807_p3;

endmodule //sobel_rgb_axis
