#include <ap_int.h>
#include <iostream>
#include <fstream>
#include <cmath>
#include <string>

// Match the type used in the core function
typedef float data;

using namespace std;

// Function declaration
void stencil2d(data surface[256][256], data output_surface[256][256], data target_time_s, data dt, data dx, data diffusivity);

int main()
{
    // Read the input generated by the python script
    ifstream file("heatmap2.txt");

    if (!file.is_open()) {
        cout << "Error: Could not open heatmap2.txt" << endl;
        return 1;
    }

    data input_surf[256][256];
    for (int y = 0; y < 256; y++){
        for (int x = 0; x < 256; x++){
            data val;
            file >> val;
            input_surf[y][x] = val;
        }
    }

    cout << "Input loaded. Starting simulation..." << endl;

    data out_surf[256][256];
    // Initialize output surface to 0 to be safe
    for(int i=0; i<256; i++)
        for(int j=0; j<256; j++)
            out_surf[i][j] = 0.0;

    data target_time_s = 12.3;
    data dt = 0.01;
    data dx = 0.001;
    data diffusivity = 0.000012;

    stencil2d(input_surf, out_surf, target_time_s, dt, dx, diffusivity);

    cout << "Simulation finished. Writing output..." << endl;

    ofstream output_file("heat_surf_out3.csv");
    for (int y4 = 0; y4 < 256; y4++)
    {
        for (int x4 = 0; x4 < 256; x4++)
        {
            double val2 = out_surf[y4][x4];
            output_file << val2 << ", ";
        }
        output_file << "\n";
    }
    output_file.close();

    cout << "Done. Output saved to heat_surf_out3.csv" << endl;
    return 0;
}
