# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ryan1/OneDrive/Desktop/ECE350_Workspace/ECE350Labs/matrix_mult_vivado/matrix_mult_vivado.srcs/sources_1/bd/design_1/ip/design_1_mult_gen_0_7/design_1_mult_gen_0_7.xci
# IP: The module: 'design_1_mult_gen_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ryan1/OneDrive/Desktop/ECE350_Workspace/ECE350Labs/matrix_mult_vivado/matrix_mult_vivado.srcs/sources_1/bd/design_1/ip/design_1_mult_gen_0_7/design_1_mult_gen_0_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mult_gen_0_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ryan1/OneDrive/Desktop/ECE350_Workspace/ECE350Labs/matrix_mult_vivado/matrix_mult_vivado.srcs/sources_1/bd/design_1/ip/design_1_mult_gen_0_7/design_1_mult_gen_0_7.xci
# IP: The module: 'design_1_mult_gen_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ryan1/OneDrive/Desktop/ECE350_Workspace/ECE350Labs/matrix_mult_vivado/matrix_mult_vivado.srcs/sources_1/bd/design_1/ip/design_1_mult_gen_0_7/design_1_mult_gen_0_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mult_gen_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
