-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_rgb_axis is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_axis_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    in_axis_TVALID : IN STD_LOGIC;
    in_axis_TREADY : OUT STD_LOGIC;
    in_axis_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    in_axis_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    in_axis_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_axis_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_axis_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_axis_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_axis_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    out_axis_TVALID : OUT STD_LOGIC;
    out_axis_TREADY : IN STD_LOGIC;
    out_axis_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    out_axis_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    out_axis_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_axis_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_axis_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_axis_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of sobel_rgb_axis is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sobel_rgb_axis,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.437000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=6,HLS_SYN_FF=1216,HLS_SYN_LUT=1496,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_96 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010010110";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv16_4D : STD_LOGIC_VECTOR (15 downto 0) := "0000000001001101";
    constant ap_const_lv14_1D : STD_LOGIC_VECTOR (13 downto 0) := "00000000011101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal line0_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal line0_V_ce0 : STD_LOGIC;
    signal line0_V_we0 : STD_LOGIC;
    signal line0_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line0_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line1_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal line1_V_ce0 : STD_LOGIC;
    signal line1_V_we0 : STD_LOGIC;
    signal line1_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line1_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_axis_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln46_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_axis_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal icmp_ln46_reg_965 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_reg_965_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal icmp_ln46_reg_965_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_reg_239 : STD_LOGIC_VECTOR (63 downto 0);
    signal y_0_reg_250 : STD_LOGIC_VECTOR (30 downto 0);
    signal w2_1_V_reg_261 : STD_LOGIC_VECTOR (7 downto 0);
    signal w2_V_1_0_reg_273 : STD_LOGIC_VECTOR (7 downto 0);
    signal w1_1_V_reg_285 : STD_LOGIC_VECTOR (7 downto 0);
    signal w1_V_1_0_reg_297 : STD_LOGIC_VECTOR (7 downto 0);
    signal w0_1_V_reg_309 : STD_LOGIC_VECTOR (7 downto 0);
    signal w0_V_1_0_reg_321 : STD_LOGIC_VECTOR (7 downto 0);
    signal x1_0_reg_333 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln39_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal x_fu_353_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln102_fu_365_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln102_reg_945 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln102_fu_376_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln102_reg_950 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln53_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_955 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state8_io : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state9_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln53_reg_955_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_955_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_reg_965_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_reg_965_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_reg_965_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln46_fu_396_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln46_7_fu_460_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln46_7_reg_974 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_keep_V_reg_979 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_keep_V_reg_979_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_keep_V_reg_979_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_keep_V_reg_979_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_keep_V_reg_979_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_strb_V_reg_984 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_strb_V_reg_984_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_strb_V_reg_984_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_strb_V_reg_984_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_strb_V_reg_984_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_id_V_reg_989 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_id_V_reg_989_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_id_V_reg_989_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_id_V_reg_989_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_id_V_reg_989_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_dest_V_reg_994 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_dest_V_reg_994_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_dest_V_reg_994_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_dest_V_reg_994_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_dest_V_reg_994_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal b_V_fu_508_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_V_reg_999 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_907_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_1_reg_1004 : STD_LOGIC_VECTOR (15 downto 0);
    signal line1_V_addr_1_reg_1009 : STD_LOGIC_VECTOR (9 downto 0);
    signal line1_V_addr_1_reg_1009_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal line0_V_addr_1_reg_1014 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln82_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln82_reg_1019 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln82_reg_1019_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln82_reg_1019_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln82_reg_1019_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln82_reg_1019_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_user_V_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_user_V_reg_1026 : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_user_V_reg_1026_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_user_V_reg_1026_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_user_V_reg_1026_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_user_V_reg_1026_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_last_V_fu_566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_last_V_reg_1031 : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_last_V_reg_1031_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_last_V_reg_1031_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_last_V_reg_1031_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_last_V_reg_1031_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_1_fu_571_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal gray_V_reg_1041 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal gray_V_reg_1041_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_reg_1041_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_2_fu_590_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_2_reg_1048 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal top1_V_reg_1053 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_8_fu_597_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_8_reg_1059 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_8_reg_1059_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_fu_604_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_reg_1064 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal select_ln46_1_fu_611_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_1_reg_1070 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_3_fu_618_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_3_reg_1075 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_4_fu_625_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_4_reg_1081 : STD_LOGIC_VECTOR (7 downto 0);
    signal top2_V_reg_1087 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln84_fu_647_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln84_reg_1093 : STD_LOGIC_VECTOR (9 downto 0);
    signal gx_fu_703_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gx_reg_1098 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_fu_767_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_reg_1103 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal x_0_reg_228 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_mux_y_0_phi_fu_254_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_mux_w2_1_V_phi_fu_265_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_w2_V_1_0_phi_fu_277_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_w1_1_V_phi_fu_289_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_w1_V_1_0_phi_fu_301_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_w0_1_V_phi_fu_313_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_w0_V_1_0_phi_fu_325_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln41_fu_359_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln63_fu_526_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln39_fu_344_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln102_fu_376_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln102_fu_376_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln53_fu_382_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln46_1_fu_410_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_416_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_2_fu_432_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln82_1_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_5_fu_402_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal r_V_fu_488_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_V_fu_498_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln215_fu_520_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_532_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln46_6_fu_448_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_2_fu_542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln101_fu_554_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln46_fu_456_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_915_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln85_1_fu_636_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln85_3_fu_643_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln85_1_fu_632_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln_fu_662_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln84_4_fu_682_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln84_1_fu_656_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln85_fu_685_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln85_2_fu_669_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln85_1_fu_691_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln86_fu_673_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln86_fu_697_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln84_3_fu_679_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1_fu_709_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln2_fu_720_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln84_fu_653_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln85_fu_659_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln88_fu_731_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln88_1_fu_737_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln88_fu_716_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln88_1_fu_741_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln88_2_fu_747_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln89_fu_727_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln84_2_fu_676_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln89_fu_757_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln89_1_fu_763_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln89_fu_751_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln82_fu_773_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln82_1_fu_783_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln82_fu_779_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_fu_793_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln91_fu_801_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln91_fu_807_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln82_1_fu_789_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_5_fu_819_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln91_1_fu_827_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln91_1_fu_833_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln91_1_fu_841_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln91_fu_815_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mag_fu_853_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_6_fu_859_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln91_fu_845_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln91_1_fu_849_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln92_fu_869_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln301_fu_875_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal edge_V_fu_881_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal edge_V_1_fu_889_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_907_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_907_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_907_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_915_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_915_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal regslice_both_out_axis_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in_axis_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_axis_TDATA_int : STD_LOGIC_VECTOR (23 downto 0);
    signal in_axis_TVALID_int : STD_LOGIC;
    signal in_axis_TREADY_int : STD_LOGIC;
    signal regslice_both_in_axis_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_axis_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_axis_TKEEP_int : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_in_axis_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_axis_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_axis_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_axis_TSTRB_int : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_in_axis_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_axis_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_axis_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_axis_TUSER_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_axis_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_axis_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_axis_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_axis_TLAST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_axis_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_axis_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_axis_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_axis_TID_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_axis_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_axis_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_axis_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_axis_TDEST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_axis_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_axis_V_dest_V_U_ack_in : STD_LOGIC;
    signal out_axis_TDATA_int : STD_LOGIC_VECTOR (23 downto 0);
    signal out_axis_TVALID_int : STD_LOGIC;
    signal out_axis_TREADY_int : STD_LOGIC;
    signal regslice_both_out_axis_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_axis_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_axis_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_axis_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_axis_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_axis_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_axis_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_axis_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_axis_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_axis_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_axis_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_axis_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_axis_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_axis_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_axis_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_axis_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_axis_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_axis_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_axis_V_dest_V_U_vld_out : STD_LOGIC;
    signal grp_fu_907_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_915_p10 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln102_fu_376_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln102_fu_376_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln215_fu_520_p10 : STD_LOGIC_VECTOR (15 downto 0);

    component sobel_rgb_axis_madEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component sobel_rgb_axis_maeOg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component sobel_rgb_axis_libkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    line0_V_U : component sobel_rgb_axis_libkb
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line0_V_address0,
        ce0 => line0_V_ce0,
        we0 => line0_V_we0,
        d0 => line0_V_d0,
        q0 => line0_V_q0);

    line1_V_U : component sobel_rgb_axis_libkb
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line1_V_address0,
        ce0 => line1_V_ce0,
        we0 => line1_V_we0,
        d0 => line1_V_d0,
        q0 => line1_V_q0);

    sobel_rgb_axis_madEe_U1 : component sobel_rgb_axis_madEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => grp_fu_907_p0,
        din1 => grp_fu_907_p1,
        din2 => grp_fu_907_p2,
        dout => grp_fu_907_p3);

    sobel_rgb_axis_maeOg_U2 : component sobel_rgb_axis_maeOg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => grp_fu_915_p0,
        din1 => grp_fu_915_p1,
        din2 => ret_V_1_reg_1004,
        dout => grp_fu_915_p3);

    regslice_both_in_axis_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_axis_TDATA,
        vld_in => in_axis_TVALID,
        ack_in => regslice_both_in_axis_V_data_V_U_ack_in,
        data_out => in_axis_TDATA_int,
        vld_out => in_axis_TVALID_int,
        ack_out => in_axis_TREADY_int,
        apdone_blk => regslice_both_in_axis_V_data_V_U_apdone_blk);

    regslice_both_in_axis_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_axis_TKEEP,
        vld_in => in_axis_TVALID,
        ack_in => regslice_both_in_axis_V_keep_V_U_ack_in,
        data_out => in_axis_TKEEP_int,
        vld_out => regslice_both_in_axis_V_keep_V_U_vld_out,
        ack_out => in_axis_TREADY_int,
        apdone_blk => regslice_both_in_axis_V_keep_V_U_apdone_blk);

    regslice_both_in_axis_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_axis_TSTRB,
        vld_in => in_axis_TVALID,
        ack_in => regslice_both_in_axis_V_strb_V_U_ack_in,
        data_out => in_axis_TSTRB_int,
        vld_out => regslice_both_in_axis_V_strb_V_U_vld_out,
        ack_out => in_axis_TREADY_int,
        apdone_blk => regslice_both_in_axis_V_strb_V_U_apdone_blk);

    regslice_both_in_axis_V_user_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_axis_TUSER,
        vld_in => in_axis_TVALID,
        ack_in => regslice_both_in_axis_V_user_V_U_ack_in,
        data_out => in_axis_TUSER_int,
        vld_out => regslice_both_in_axis_V_user_V_U_vld_out,
        ack_out => in_axis_TREADY_int,
        apdone_blk => regslice_both_in_axis_V_user_V_U_apdone_blk);

    regslice_both_in_axis_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_axis_TLAST,
        vld_in => in_axis_TVALID,
        ack_in => regslice_both_in_axis_V_last_V_U_ack_in,
        data_out => in_axis_TLAST_int,
        vld_out => regslice_both_in_axis_V_last_V_U_vld_out,
        ack_out => in_axis_TREADY_int,
        apdone_blk => regslice_both_in_axis_V_last_V_U_apdone_blk);

    regslice_both_in_axis_V_id_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_axis_TID,
        vld_in => in_axis_TVALID,
        ack_in => regslice_both_in_axis_V_id_V_U_ack_in,
        data_out => in_axis_TID_int,
        vld_out => regslice_both_in_axis_V_id_V_U_vld_out,
        ack_out => in_axis_TREADY_int,
        apdone_blk => regslice_both_in_axis_V_id_V_U_apdone_blk);

    regslice_both_in_axis_V_dest_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_axis_TDEST,
        vld_in => in_axis_TVALID,
        ack_in => regslice_both_in_axis_V_dest_V_U_ack_in,
        data_out => in_axis_TDEST_int,
        vld_out => regslice_both_in_axis_V_dest_V_U_vld_out,
        ack_out => in_axis_TREADY_int,
        apdone_blk => regslice_both_in_axis_V_dest_V_U_apdone_blk);

    regslice_both_out_axis_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_axis_TDATA_int,
        vld_in => out_axis_TVALID_int,
        ack_in => out_axis_TREADY_int,
        data_out => out_axis_TDATA,
        vld_out => regslice_both_out_axis_V_data_V_U_vld_out,
        ack_out => out_axis_TREADY,
        apdone_blk => regslice_both_out_axis_V_data_V_U_apdone_blk);

    regslice_both_out_axis_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_keep_V_reg_979_pp0_iter4_reg,
        vld_in => out_axis_TVALID_int,
        ack_in => regslice_both_out_axis_V_keep_V_U_ack_in_dummy,
        data_out => out_axis_TKEEP,
        vld_out => regslice_both_out_axis_V_keep_V_U_vld_out,
        ack_out => out_axis_TREADY,
        apdone_blk => regslice_both_out_axis_V_keep_V_U_apdone_blk);

    regslice_both_out_axis_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_strb_V_reg_984_pp0_iter4_reg,
        vld_in => out_axis_TVALID_int,
        ack_in => regslice_both_out_axis_V_strb_V_U_ack_in_dummy,
        data_out => out_axis_TSTRB,
        vld_out => regslice_both_out_axis_V_strb_V_U_vld_out,
        ack_out => out_axis_TREADY,
        apdone_blk => regslice_both_out_axis_V_strb_V_U_apdone_blk);

    regslice_both_out_axis_V_user_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => dout_user_V_reg_1026_pp0_iter4_reg,
        vld_in => out_axis_TVALID_int,
        ack_in => regslice_both_out_axis_V_user_V_U_ack_in_dummy,
        data_out => out_axis_TUSER,
        vld_out => regslice_both_out_axis_V_user_V_U_vld_out,
        ack_out => out_axis_TREADY,
        apdone_blk => regslice_both_out_axis_V_user_V_U_apdone_blk);

    regslice_both_out_axis_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => dout_last_V_reg_1031_pp0_iter4_reg,
        vld_in => out_axis_TVALID_int,
        ack_in => regslice_both_out_axis_V_last_V_U_ack_in_dummy,
        data_out => out_axis_TLAST,
        vld_out => regslice_both_out_axis_V_last_V_U_vld_out,
        ack_out => out_axis_TREADY,
        apdone_blk => regslice_both_out_axis_V_last_V_U_apdone_blk);

    regslice_both_out_axis_V_id_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_id_V_reg_989_pp0_iter4_reg,
        vld_in => out_axis_TVALID_int,
        ack_in => regslice_both_out_axis_V_id_V_U_ack_in_dummy,
        data_out => out_axis_TID,
        vld_out => regslice_both_out_axis_V_id_V_U_vld_out,
        ack_out => out_axis_TREADY,
        apdone_blk => regslice_both_out_axis_V_id_V_U_apdone_blk);

    regslice_both_out_axis_V_dest_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_dest_V_reg_994_pp0_iter4_reg,
        vld_in => out_axis_TVALID_int,
        ack_in => regslice_both_out_axis_V_dest_V_U_ack_in_dummy,
        data_out => out_axis_TDEST,
        vld_out => regslice_both_out_axis_V_dest_V_U_vld_out,
        ack_out => out_axis_TREADY,
        apdone_blk => regslice_both_out_axis_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                elsif (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_reg_239_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_fu_391_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_239 <= add_ln46_fu_396_p2;
            elsif (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                indvar_flatten_reg_239 <= ap_const_lv64_0;
            end if; 
        end if;
    end process;

    w0_1_V_reg_309_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                w0_1_V_reg_309 <= top2_V_reg_1087;
            elsif (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                w0_1_V_reg_309 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    w0_V_1_0_reg_321_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                w0_V_1_0_reg_321 <= select_ln46_3_reg_1075;
            elsif (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                w0_V_1_0_reg_321 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    w1_1_V_reg_285_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                w1_1_V_reg_285 <= top1_V_reg_1053;
            elsif (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                w1_1_V_reg_285 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    w1_V_1_0_reg_297_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                w1_V_1_0_reg_297 <= select_ln46_2_reg_1048;
            elsif (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                w1_V_1_0_reg_297 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    w2_1_V_reg_261_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                w2_1_V_reg_261 <= gray_V_reg_1041_pp0_iter3_reg;
            elsif (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                w2_1_V_reg_261 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    w2_V_1_0_reg_273_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                w2_V_1_0_reg_273 <= select_ln46_reg_1064;
            elsif (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                w2_V_1_0_reg_273 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    x1_0_reg_333_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_fu_391_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                x1_0_reg_333 <= x_1_fu_571_p2;
            elsif (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                x1_0_reg_333 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    x_0_reg_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln39_fu_348_p2 = ap_const_lv1_1))) then 
                x_0_reg_228 <= x_fu_353_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                x_0_reg_228 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    y_0_reg_250_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                y_0_reg_250 <= select_ln46_7_reg_974;
            elsif (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_0_reg_250 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                add_ln102_reg_945 <= add_ln102_fu_365_p2;
                mul_ln102_reg_950 <= mul_ln102_fu_376_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln82_reg_1019_pp0_iter2_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln84_reg_1093 <= add_ln84_fu_647_p2;
                select_ln46_1_reg_1070 <= select_ln46_1_fu_611_p3;
                select_ln46_4_reg_1081 <= select_ln46_4_fu_625_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_fu_391_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln82_reg_1019 <= and_ln82_fu_548_p2;
                b_V_reg_999 <= b_V_fu_508_p1;
                dout_last_V_reg_1031 <= dout_last_V_fu_566_p2;
                dout_user_V_reg_1026 <= dout_user_V_fu_560_p2;
                line0_V_addr_1_reg_1014 <= zext_ln63_fu_526_p1(10 - 1 downto 0);
                line1_V_addr_1_reg_1009 <= zext_ln63_fu_526_p1(10 - 1 downto 0);
                tmp_dest_V_reg_994 <= in_axis_TDEST_int;
                tmp_id_V_reg_989 <= in_axis_TID_int;
                tmp_keep_V_reg_979 <= in_axis_TKEEP_int;
                tmp_strb_V_reg_984 <= in_axis_TSTRB_int;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln82_reg_1019_pp0_iter1_reg <= and_ln82_reg_1019;
                dout_last_V_reg_1031_pp0_iter1_reg <= dout_last_V_reg_1031;
                dout_user_V_reg_1026_pp0_iter1_reg <= dout_user_V_reg_1026;
                icmp_ln46_reg_965 <= icmp_ln46_fu_391_p2;
                icmp_ln46_reg_965_pp0_iter1_reg <= icmp_ln46_reg_965;
                icmp_ln53_reg_955 <= icmp_ln53_fu_386_p2;
                icmp_ln53_reg_955_pp0_iter1_reg <= icmp_ln53_reg_955;
                line1_V_addr_1_reg_1009_pp0_iter1_reg <= line1_V_addr_1_reg_1009;
                tmp_dest_V_reg_994_pp0_iter1_reg <= tmp_dest_V_reg_994;
                tmp_id_V_reg_989_pp0_iter1_reg <= tmp_id_V_reg_989;
                tmp_keep_V_reg_979_pp0_iter1_reg <= tmp_keep_V_reg_979;
                tmp_strb_V_reg_984_pp0_iter1_reg <= tmp_strb_V_reg_984;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln82_reg_1019_pp0_iter2_reg <= and_ln82_reg_1019_pp0_iter1_reg;
                and_ln82_reg_1019_pp0_iter3_reg <= and_ln82_reg_1019_pp0_iter2_reg;
                and_ln82_reg_1019_pp0_iter4_reg <= and_ln82_reg_1019_pp0_iter3_reg;
                dout_last_V_reg_1031_pp0_iter2_reg <= dout_last_V_reg_1031_pp0_iter1_reg;
                dout_last_V_reg_1031_pp0_iter3_reg <= dout_last_V_reg_1031_pp0_iter2_reg;
                dout_last_V_reg_1031_pp0_iter4_reg <= dout_last_V_reg_1031_pp0_iter3_reg;
                dout_user_V_reg_1026_pp0_iter2_reg <= dout_user_V_reg_1026_pp0_iter1_reg;
                dout_user_V_reg_1026_pp0_iter3_reg <= dout_user_V_reg_1026_pp0_iter2_reg;
                dout_user_V_reg_1026_pp0_iter4_reg <= dout_user_V_reg_1026_pp0_iter3_reg;
                gray_V_reg_1041_pp0_iter2_reg <= gray_V_reg_1041;
                gray_V_reg_1041_pp0_iter3_reg <= gray_V_reg_1041_pp0_iter2_reg;
                icmp_ln46_reg_965_pp0_iter2_reg <= icmp_ln46_reg_965_pp0_iter1_reg;
                icmp_ln46_reg_965_pp0_iter3_reg <= icmp_ln46_reg_965_pp0_iter2_reg;
                icmp_ln46_reg_965_pp0_iter4_reg <= icmp_ln46_reg_965_pp0_iter3_reg;
                icmp_ln46_reg_965_pp0_iter5_reg <= icmp_ln46_reg_965_pp0_iter4_reg;
                icmp_ln53_reg_955_pp0_iter2_reg <= icmp_ln53_reg_955_pp0_iter1_reg;
                select_ln46_8_reg_1059_pp0_iter3_reg <= select_ln46_8_reg_1059;
                tmp_dest_V_reg_994_pp0_iter2_reg <= tmp_dest_V_reg_994_pp0_iter1_reg;
                tmp_dest_V_reg_994_pp0_iter3_reg <= tmp_dest_V_reg_994_pp0_iter2_reg;
                tmp_dest_V_reg_994_pp0_iter4_reg <= tmp_dest_V_reg_994_pp0_iter3_reg;
                tmp_id_V_reg_989_pp0_iter2_reg <= tmp_id_V_reg_989_pp0_iter1_reg;
                tmp_id_V_reg_989_pp0_iter3_reg <= tmp_id_V_reg_989_pp0_iter2_reg;
                tmp_id_V_reg_989_pp0_iter4_reg <= tmp_id_V_reg_989_pp0_iter3_reg;
                tmp_keep_V_reg_979_pp0_iter2_reg <= tmp_keep_V_reg_979_pp0_iter1_reg;
                tmp_keep_V_reg_979_pp0_iter3_reg <= tmp_keep_V_reg_979_pp0_iter2_reg;
                tmp_keep_V_reg_979_pp0_iter4_reg <= tmp_keep_V_reg_979_pp0_iter3_reg;
                tmp_strb_V_reg_984_pp0_iter2_reg <= tmp_strb_V_reg_984_pp0_iter1_reg;
                tmp_strb_V_reg_984_pp0_iter3_reg <= tmp_strb_V_reg_984_pp0_iter2_reg;
                tmp_strb_V_reg_984_pp0_iter4_reg <= tmp_strb_V_reg_984_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                gray_V_reg_1041 <= grp_fu_915_p3(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln82_reg_1019_pp0_iter3_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                gx_reg_1098 <= gx_fu_703_p2;
                gy_reg_1103 <= gy_fu_767_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_fu_391_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ret_V_1_reg_1004 <= grp_fu_907_p3;
                select_ln46_7_reg_974 <= select_ln46_7_fu_460_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln46_2_reg_1048 <= select_ln46_2_fu_590_p3;
                top1_V_reg_1053 <= line0_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln46_3_reg_1075 <= select_ln46_3_fu_618_p3;
                top2_V_reg_1087 <= line1_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln82_reg_1019_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln46_8_reg_1059 <= select_ln46_8_fu_597_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln46_reg_965_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln82_reg_1019_pp0_iter2_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln46_reg_1064 <= select_ln46_fu_604_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter0, icmp_ln46_fu_391_p2, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, icmp_ln39_fu_348_p2, ap_CS_fsm_state2, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, ap_CS_fsm_state10, regslice_both_out_axis_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln39_fu_348_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln46_fu_391_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((icmp_ln46_fu_391_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state10 => 
                if (((regslice_both_out_axis_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln102_fu_365_p2 <= std_logic_vector(unsigned(width) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln301_fu_875_p2 <= std_logic_vector(unsigned(trunc_ln91_fu_845_p1) + unsigned(trunc_ln91_1_fu_849_p1));
    add_ln46_1_fu_410_p2 <= std_logic_vector(unsigned(ap_const_lv31_1) + unsigned(ap_phi_mux_y_0_phi_fu_254_p4));
    add_ln46_fu_396_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_239) + unsigned(ap_const_lv64_1));
    add_ln84_fu_647_p2 <= std_logic_vector(unsigned(zext_ln85_3_fu_643_p1) + unsigned(zext_ln85_1_fu_632_p1));
    add_ln88_1_fu_741_p2 <= std_logic_vector(unsigned(zext_ln88_1_fu_737_p1) + unsigned(zext_ln88_fu_716_p1));
    add_ln88_fu_731_p2 <= std_logic_vector(unsigned(zext_ln84_fu_653_p1) + unsigned(zext_ln85_fu_659_p1));
    add_ln89_fu_757_p2 <= std_logic_vector(unsigned(zext_ln89_fu_727_p1) + unsigned(zext_ln84_2_fu_676_p1));
    and_ln82_fu_548_p2 <= (select_ln46_6_fu_448_p3 and icmp_ln82_2_fu_542_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(3);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln46_fu_391_p2, in_axis_TVALID_int)
    begin
                ap_block_pp0_stage0_01001 <= ((icmp_ln46_fu_391_p2 = ap_const_lv1_0) and (in_axis_TVALID_int = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln46_fu_391_p2, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_block_state8_io, ap_block_state9_io, in_axis_TVALID_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_boolean_1 = ap_block_state9_io) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state8_io) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((icmp_ln46_fu_391_p2 = ap_const_lv1_0) and (in_axis_TVALID_int = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln46_fu_391_p2, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_block_state8_io, ap_block_state9_io, in_axis_TVALID_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_boolean_1 = ap_block_state9_io) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state8_io) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((icmp_ln46_fu_391_p2 = ap_const_lv1_0) and (in_axis_TVALID_int = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_state3_pp0_stage0_iter0_assign_proc : process(icmp_ln46_fu_391_p2, in_axis_TVALID_int)
    begin
                ap_block_state3_pp0_stage0_iter0 <= ((icmp_ln46_fu_391_p2 = ap_const_lv1_0) and (in_axis_TVALID_int = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_io_assign_proc : process(icmp_ln46_reg_965_pp0_iter4_reg, out_axis_TREADY_int)
    begin
                ap_block_state8_io <= ((icmp_ln46_reg_965_pp0_iter4_reg = ap_const_lv1_0) and (out_axis_TREADY_int = ap_const_logic_0));
    end process;

        ap_block_state8_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_io_assign_proc : process(icmp_ln46_reg_965_pp0_iter5_reg, out_axis_TREADY_int)
    begin
                ap_block_state9_io <= ((icmp_ln46_reg_965_pp0_iter5_reg = ap_const_lv1_0) and (out_axis_TREADY_int = ap_const_logic_0));
    end process;

        ap_block_state9_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln46_fu_391_p2)
    begin
        if ((icmp_ln46_fu_391_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state10, regslice_both_out_axis_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_axis_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_w0_1_V_phi_fu_313_p4_assign_proc : process(ap_block_pp0_stage0, w0_1_V_reg_309, icmp_ln46_reg_965_pp0_iter3_reg, top2_V_reg_1087, ap_enable_reg_pp0_iter4)
    begin
        if (((icmp_ln46_reg_965_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            ap_phi_mux_w0_1_V_phi_fu_313_p4 <= top2_V_reg_1087;
        else 
            ap_phi_mux_w0_1_V_phi_fu_313_p4 <= w0_1_V_reg_309;
        end if; 
    end process;


    ap_phi_mux_w0_V_1_0_phi_fu_325_p4_assign_proc : process(ap_block_pp0_stage0, w0_V_1_0_reg_321, icmp_ln46_reg_965_pp0_iter3_reg, select_ln46_3_reg_1075, ap_enable_reg_pp0_iter4)
    begin
        if (((icmp_ln46_reg_965_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            ap_phi_mux_w0_V_1_0_phi_fu_325_p4 <= select_ln46_3_reg_1075;
        else 
            ap_phi_mux_w0_V_1_0_phi_fu_325_p4 <= w0_V_1_0_reg_321;
        end if; 
    end process;


    ap_phi_mux_w1_1_V_phi_fu_289_p4_assign_proc : process(ap_block_pp0_stage0, w1_1_V_reg_285, icmp_ln46_reg_965_pp0_iter2_reg, top1_V_reg_1053, ap_enable_reg_pp0_iter3)
    begin
        if (((icmp_ln46_reg_965_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_phi_mux_w1_1_V_phi_fu_289_p4 <= top1_V_reg_1053;
        else 
            ap_phi_mux_w1_1_V_phi_fu_289_p4 <= w1_1_V_reg_285;
        end if; 
    end process;


    ap_phi_mux_w1_V_1_0_phi_fu_301_p4_assign_proc : process(ap_block_pp0_stage0, w1_V_1_0_reg_297, icmp_ln46_reg_965_pp0_iter2_reg, select_ln46_2_reg_1048, ap_enable_reg_pp0_iter3)
    begin
        if (((icmp_ln46_reg_965_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_phi_mux_w1_V_1_0_phi_fu_301_p4 <= select_ln46_2_reg_1048;
        else 
            ap_phi_mux_w1_V_1_0_phi_fu_301_p4 <= w1_V_1_0_reg_297;
        end if; 
    end process;


    ap_phi_mux_w2_1_V_phi_fu_265_p4_assign_proc : process(ap_block_pp0_stage0, w2_1_V_reg_261, icmp_ln46_reg_965_pp0_iter3_reg, gray_V_reg_1041_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((icmp_ln46_reg_965_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            ap_phi_mux_w2_1_V_phi_fu_265_p4 <= gray_V_reg_1041_pp0_iter3_reg;
        else 
            ap_phi_mux_w2_1_V_phi_fu_265_p4 <= w2_1_V_reg_261;
        end if; 
    end process;


    ap_phi_mux_w2_V_1_0_phi_fu_277_p4_assign_proc : process(ap_block_pp0_stage0, w2_V_1_0_reg_273, icmp_ln46_reg_965_pp0_iter3_reg, select_ln46_reg_1064, ap_enable_reg_pp0_iter4)
    begin
        if (((icmp_ln46_reg_965_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            ap_phi_mux_w2_V_1_0_phi_fu_277_p4 <= select_ln46_reg_1064;
        else 
            ap_phi_mux_w2_V_1_0_phi_fu_277_p4 <= w2_V_1_0_reg_273;
        end if; 
    end process;


    ap_phi_mux_y_0_phi_fu_254_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, icmp_ln46_reg_965, y_0_reg_250, select_ln46_7_reg_974, ap_enable_reg_pp0_iter1)
    begin
        if (((icmp_ln46_reg_965 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_y_0_phi_fu_254_p4 <= select_ln46_7_reg_974;
        else 
            ap_phi_mux_y_0_phi_fu_254_p4 <= y_0_reg_250;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state10, regslice_both_out_axis_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_axis_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    b_V_fu_508_p1 <= in_axis_TDATA_int(8 - 1 downto 0);
    dout_last_V_fu_566_p2 <= "1" when (zext_ln46_fu_456_p1 = add_ln102_reg_945) else "0";
    dout_user_V_fu_560_p2 <= "1" when (or_ln101_fu_554_p2 = ap_const_lv31_0) else "0";
    edge_V_1_fu_889_p3 <= 
        edge_V_fu_881_p3 when (and_ln82_reg_1019_pp0_iter4_reg(0) = '1') else 
        ap_const_lv8_0;
    edge_V_fu_881_p3 <= 
        ap_const_lv8_FF when (icmp_ln92_fu_869_p2(0) = '1') else 
        add_ln301_fu_875_p2;
    g_V_fu_498_p4 <= in_axis_TDATA_int(15 downto 8);
    grp_fu_907_p0 <= ap_const_lv16_4D(8 - 1 downto 0);
    grp_fu_907_p1 <= grp_fu_907_p10(8 - 1 downto 0);
    grp_fu_907_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_fu_488_p4),16));
    grp_fu_907_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_const_lv16_96) * unsigned(mul_ln215_fu_520_p1), 16));
    grp_fu_915_p0 <= ap_const_lv14_1D(6 - 1 downto 0);
    grp_fu_915_p1 <= grp_fu_915_p10(8 - 1 downto 0);
    grp_fu_915_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_V_reg_999),14));
    gx_fu_703_p2 <= std_logic_vector(unsigned(sub_ln86_fu_697_p2) + unsigned(zext_ln84_3_fu_679_p1));
    gy_fu_767_p2 <= std_logic_vector(unsigned(zext_ln89_1_fu_763_p1) + unsigned(sub_ln89_fu_751_p2));
    icmp_ln39_fu_348_p2 <= "1" when (signed(zext_ln39_fu_344_p1) < signed(width)) else "0";
    icmp_ln46_fu_391_p2 <= "1" when (indvar_flatten_reg_239 = mul_ln102_reg_950) else "0";
    icmp_ln53_fu_386_p2 <= "1" when (signed(zext_ln53_fu_382_p1) < signed(width)) else "0";
    icmp_ln82_1_fu_442_p2 <= "0" when (tmp_2_fu_432_p4 = ap_const_lv30_0) else "1";
    icmp_ln82_2_fu_542_p2 <= "0" when (tmp_3_fu_532_p4 = ap_const_lv30_0) else "1";
    icmp_ln82_fu_426_p2 <= "0" when (tmp_fu_416_p4 = ap_const_lv30_0) else "1";
    icmp_ln92_fu_869_p2 <= "0" when (tmp_6_fu_859_p4 = ap_const_lv3_0) else "1";

    in_axis_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln46_fu_391_p2, in_axis_TVALID_int)
    begin
        if (((icmp_ln46_fu_391_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_axis_TDATA_blk_n <= in_axis_TVALID_int;
        else 
            in_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_axis_TREADY_assign_proc : process(in_axis_TVALID, regslice_both_in_axis_V_data_V_U_ack_in)
    begin
        if (((regslice_both_in_axis_V_data_V_U_ack_in = ap_const_logic_1) and (in_axis_TVALID = ap_const_logic_1))) then 
            in_axis_TREADY <= ap_const_logic_1;
        else 
            in_axis_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    in_axis_TREADY_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln46_fu_391_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln46_fu_391_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            in_axis_TREADY_int <= ap_const_logic_1;
        else 
            in_axis_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    line0_V_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, icmp_ln46_reg_965, ap_CS_fsm_state2, line0_V_addr_1_reg_1014, ap_enable_reg_pp0_iter1, zext_ln41_fu_359_p1)
    begin
        if (((icmp_ln46_reg_965 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            line0_V_address0 <= line0_V_addr_1_reg_1014;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line0_V_address0 <= zext_ln41_fu_359_p1(10 - 1 downto 0);
        else 
            line0_V_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    line0_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln46_reg_965, ap_CS_fsm_state2, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((icmp_ln46_reg_965 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            line0_V_ce0 <= ap_const_logic_1;
        else 
            line0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line0_V_d0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, icmp_ln46_reg_965, ap_CS_fsm_state2, ap_enable_reg_pp0_iter1, grp_fu_915_p3)
    begin
        if (((icmp_ln46_reg_965 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            line0_V_d0 <= grp_fu_915_p3(15 downto 8);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line0_V_d0 <= ap_const_lv8_0;
        else 
            line0_V_d0 <= "XXXXXXXX";
        end if; 
    end process;


    line0_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln46_reg_965, icmp_ln39_fu_348_p2, ap_CS_fsm_state2, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if ((((icmp_ln46_reg_965 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln39_fu_348_p2 = ap_const_lv1_1)))) then 
            line0_V_we0 <= ap_const_logic_1;
        else 
            line0_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line1_V_address0_assign_proc : process(ap_block_pp0_stage0, ap_CS_fsm_state2, icmp_ln46_reg_965_pp0_iter1_reg, line1_V_addr_1_reg_1009_pp0_iter1_reg, ap_enable_reg_pp0_iter2, zext_ln41_fu_359_p1)
    begin
        if (((icmp_ln46_reg_965_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            line1_V_address0 <= line1_V_addr_1_reg_1009_pp0_iter1_reg;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line1_V_address0 <= zext_ln41_fu_359_p1(10 - 1 downto 0);
        else 
            line1_V_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    line1_V_ce0_assign_proc : process(ap_CS_fsm_state2, ap_block_pp0_stage0_11001, icmp_ln46_reg_965_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((icmp_ln46_reg_965_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            line1_V_ce0 <= ap_const_logic_1;
        else 
            line1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line1_V_d0_assign_proc : process(line0_V_q0, ap_block_pp0_stage0, ap_CS_fsm_state2, icmp_ln46_reg_965_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((icmp_ln46_reg_965_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            line1_V_d0 <= line0_V_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line1_V_d0 <= ap_const_lv8_0;
        else 
            line1_V_d0 <= "XXXXXXXX";
        end if; 
    end process;


    line1_V_we0_assign_proc : process(icmp_ln39_fu_348_p2, ap_CS_fsm_state2, ap_block_pp0_stage0_11001, icmp_ln46_reg_965_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if ((((icmp_ln46_reg_965_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln39_fu_348_p2 = ap_const_lv1_1)))) then 
            line1_V_we0 <= ap_const_logic_1;
        else 
            line1_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    mag_fu_853_p2 <= std_logic_vector(unsigned(zext_ln91_1_fu_841_p1) + unsigned(zext_ln91_fu_815_p1));
    mul_ln102_fu_376_p0 <= mul_ln102_fu_376_p00(32 - 1 downto 0);
    mul_ln102_fu_376_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),64));
    mul_ln102_fu_376_p1 <= mul_ln102_fu_376_p10(32 - 1 downto 0);
    mul_ln102_fu_376_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),64));
    mul_ln102_fu_376_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln102_fu_376_p0) * unsigned(mul_ln102_fu_376_p1), 64));
    mul_ln215_fu_520_p1 <= mul_ln215_fu_520_p10(8 - 1 downto 0);
    mul_ln215_fu_520_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_V_fu_498_p4),16));
    or_ln101_fu_554_p2 <= (select_ln46_7_fu_460_p3 or select_ln46_5_fu_402_p3);

    out_axis_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter5, icmp_ln46_reg_965_pp0_iter4_reg, ap_enable_reg_pp0_iter6, icmp_ln46_reg_965_pp0_iter5_reg, out_axis_TREADY_int)
    begin
        if ((((icmp_ln46_reg_965_pp0_iter5_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((icmp_ln46_reg_965_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)))) then 
            out_axis_TDATA_blk_n <= out_axis_TREADY_int;
        else 
            out_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_axis_TDATA_int <= ((edge_V_1_fu_889_p3 & edge_V_1_fu_889_p3) & edge_V_1_fu_889_p3);
    out_axis_TVALID <= regslice_both_out_axis_V_data_V_U_vld_out;

    out_axis_TVALID_int_assign_proc : process(ap_enable_reg_pp0_iter5, icmp_ln46_reg_965_pp0_iter4_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln46_reg_965_pp0_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            out_axis_TVALID_int <= ap_const_logic_1;
        else 
            out_axis_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    r_V_fu_488_p4 <= in_axis_TDATA_int(23 downto 16);
    select_ln46_1_fu_611_p3 <= 
        ap_phi_mux_w2_V_1_0_phi_fu_277_p4 when (icmp_ln53_reg_955_pp0_iter2_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln46_2_fu_590_p3 <= 
        ap_phi_mux_w1_1_V_phi_fu_289_p4 when (icmp_ln53_reg_955_pp0_iter1_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln46_3_fu_618_p3 <= 
        ap_phi_mux_w0_1_V_phi_fu_313_p4 when (icmp_ln53_reg_955_pp0_iter2_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln46_4_fu_625_p3 <= 
        ap_phi_mux_w0_V_1_0_phi_fu_325_p4 when (icmp_ln53_reg_955_pp0_iter2_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln46_5_fu_402_p3 <= 
        x1_0_reg_333 when (icmp_ln53_fu_386_p2(0) = '1') else 
        ap_const_lv31_0;
    select_ln46_6_fu_448_p3 <= 
        icmp_ln82_1_fu_442_p2 when (icmp_ln53_fu_386_p2(0) = '1') else 
        icmp_ln82_fu_426_p2;
    select_ln46_7_fu_460_p3 <= 
        ap_phi_mux_y_0_phi_fu_254_p4 when (icmp_ln53_fu_386_p2(0) = '1') else 
        add_ln46_1_fu_410_p2;
    select_ln46_8_fu_597_p3 <= 
        ap_phi_mux_w1_V_1_0_phi_fu_301_p4 when (icmp_ln53_reg_955_pp0_iter1_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln46_fu_604_p3 <= 
        ap_phi_mux_w2_1_V_phi_fu_265_p4 when (icmp_ln53_reg_955_pp0_iter2_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln82_1_fu_783_p3 <= 
        gy_reg_1103 when (and_ln82_reg_1019_pp0_iter4_reg(0) = '1') else 
        ap_const_lv11_0;
    select_ln82_fu_773_p3 <= 
        gx_reg_1098 when (and_ln82_reg_1019_pp0_iter4_reg(0) = '1') else 
        ap_const_lv11_0;
    select_ln91_1_fu_833_p3 <= 
        sub_ln91_1_fu_827_p2 when (tmp_5_fu_819_p3(0) = '1') else 
        trunc_ln82_1_fu_789_p1;
    select_ln91_fu_807_p3 <= 
        sub_ln91_fu_801_p2 when (tmp_4_fu_793_p3(0) = '1') else 
        trunc_ln82_fu_779_p1;
    shl_ln1_fu_709_p3 <= (select_ln46_3_reg_1075 & ap_const_lv1_0);
    shl_ln2_fu_720_p3 <= (select_ln46_reg_1064 & ap_const_lv1_0);
    shl_ln85_1_fu_636_p3 <= (top1_V_reg_1053 & ap_const_lv1_0);
    shl_ln_fu_662_p3 <= (select_ln46_8_reg_1059_pp0_iter3_reg & ap_const_lv1_0);
    sub_ln85_1_fu_691_p2 <= std_logic_vector(unsigned(sub_ln85_fu_685_p2) - unsigned(zext_ln85_2_fu_669_p1));
    sub_ln85_fu_685_p2 <= std_logic_vector(unsigned(zext_ln84_4_fu_682_p1) - unsigned(zext_ln84_1_fu_656_p1));
    sub_ln86_fu_697_p2 <= std_logic_vector(unsigned(sub_ln85_1_fu_691_p2) - unsigned(zext_ln86_fu_673_p1));
    sub_ln89_fu_751_p2 <= std_logic_vector(unsigned(zext_ln86_fu_673_p1) - unsigned(zext_ln88_2_fu_747_p1));
    sub_ln91_1_fu_827_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(trunc_ln82_1_fu_789_p1));
    sub_ln91_fu_801_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(trunc_ln82_fu_779_p1));
    tmp_2_fu_432_p4 <= ap_phi_mux_y_0_phi_fu_254_p4(30 downto 1);
    tmp_3_fu_532_p4 <= select_ln46_5_fu_402_p3(30 downto 1);
    tmp_4_fu_793_p3 <= select_ln82_fu_773_p3(10 downto 10);
    tmp_5_fu_819_p3 <= select_ln82_1_fu_783_p3(10 downto 10);
    tmp_6_fu_859_p4 <= mag_fu_853_p2(10 downto 8);
    tmp_fu_416_p4 <= add_ln46_1_fu_410_p2(30 downto 1);
    trunc_ln82_1_fu_789_p1 <= select_ln82_1_fu_783_p3(10 - 1 downto 0);
    trunc_ln82_fu_779_p1 <= select_ln82_fu_773_p3(10 - 1 downto 0);
    trunc_ln91_1_fu_849_p1 <= select_ln91_1_fu_833_p3(8 - 1 downto 0);
    trunc_ln91_fu_845_p1 <= select_ln91_fu_807_p3(8 - 1 downto 0);
    x_1_fu_571_p2 <= std_logic_vector(unsigned(ap_const_lv31_1) + unsigned(select_ln46_5_fu_402_p3));
    x_fu_353_p2 <= std_logic_vector(unsigned(x_0_reg_228) + unsigned(ap_const_lv31_1));
    zext_ln39_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_0_reg_228),32));
    zext_ln41_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_0_reg_228),64));
    zext_ln46_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln46_5_fu_402_p3),32));
    zext_ln53_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x1_0_reg_333),32));
    zext_ln63_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln46_5_fu_402_p3),64));
    zext_ln84_1_fu_656_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln46_4_reg_1081),11));
    zext_ln84_2_fu_676_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gray_V_reg_1041_pp0_iter3_reg),10));
    zext_ln84_3_fu_679_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gray_V_reg_1041_pp0_iter3_reg),11));
    zext_ln84_4_fu_682_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln84_reg_1093),11));
    zext_ln84_fu_653_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln46_4_reg_1081),9));
    zext_ln85_1_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(line1_V_q0),10));
    zext_ln85_2_fu_669_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_662_p3),11));
    zext_ln85_3_fu_643_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln85_1_fu_636_p3),10));
    zext_ln85_fu_659_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(top2_V_reg_1087),9));
    zext_ln86_fu_673_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln46_1_reg_1070),11));
    zext_ln88_1_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln88_fu_731_p2),10));
    zext_ln88_2_fu_747_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln88_1_fu_741_p2),11));
    zext_ln88_fu_716_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_709_p3),10));
    zext_ln89_1_fu_763_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln89_fu_757_p2),11));
    zext_ln89_fu_727_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_720_p3),10));
    zext_ln91_1_fu_841_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln91_1_fu_833_p3),11));
    zext_ln91_fu_815_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln91_fu_807_p3),11));
end behav;
