# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mult_gen_0_0/design_1_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mult_gen_0_0 || ORIG_REF_NAME==design_1_mult_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mult_gen_0_1/design_1_mult_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mult_gen_0_1 || ORIG_REF_NAME==design_1_mult_gen_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mult_gen_0_2/design_1_mult_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mult_gen_0_2 || ORIG_REF_NAME==design_1_mult_gen_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mult_gen_0_3/design_1_mult_gen_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mult_gen_0_3 || ORIG_REF_NAME==design_1_mult_gen_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mult_gen_0_4/design_1_mult_gen_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mult_gen_0_4 || ORIG_REF_NAME==design_1_mult_gen_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mult_gen_0_5/design_1_mult_gen_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mult_gen_0_5 || ORIG_REF_NAME==design_1_mult_gen_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mult_gen_0_6/design_1_mult_gen_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mult_gen_0_6 || ORIG_REF_NAME==design_1_mult_gen_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mult_gen_0_7/design_1_mult_gen_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mult_gen_0_7 || ORIG_REF_NAME==design_1_mult_gen_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_addsub_0_0/design_1_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_addsub_0_0 || ORIG_REF_NAME==design_1_c_addsub_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_addsub_0_1/design_1_c_addsub_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_addsub_0_1 || ORIG_REF_NAME==design_1_c_addsub_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_addsub_0_2/design_1_c_addsub_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_addsub_0_2 || ORIG_REF_NAME==design_1_c_addsub_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_addsub_0_3/design_1_c_addsub_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_addsub_0_3 || ORIG_REF_NAME==design_1_c_addsub_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_2/design_1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_2 || ORIG_REF_NAME==design_1_xlslice_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_3/design_1_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_3 || ORIG_REF_NAME==design_1_xlslice_0_3} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
