#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("in_axis_TDATA", 24, hls_in, 0, "axis", "in_data", 1),
	Port_Property("in_axis_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("in_axis_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("in_axis_TKEEP", 3, hls_in, 1, "axis", "in_data", 1),
	Port_Property("in_axis_TSTRB", 3, hls_in, 2, "axis", "in_data", 1),
	Port_Property("in_axis_TUSER", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("in_axis_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("in_axis_TID", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("in_axis_TDEST", 1, hls_in, 6, "axis", "in_data", 1),
	Port_Property("out_axis_TDATA", 24, hls_out, 7, "axis", "out_data", 1),
	Port_Property("out_axis_TVALID", 1, hls_out, 13, "axis", "out_vld", 1),
	Port_Property("out_axis_TREADY", 1, hls_in, 13, "axis", "out_acc", 1),
	Port_Property("out_axis_TKEEP", 3, hls_out, 8, "axis", "out_data", 1),
	Port_Property("out_axis_TSTRB", 3, hls_out, 9, "axis", "out_data", 1),
	Port_Property("out_axis_TUSER", 1, hls_out, 10, "axis", "out_data", 1),
	Port_Property("out_axis_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("out_axis_TID", 1, hls_out, 12, "axis", "out_data", 1),
	Port_Property("out_axis_TDEST", 1, hls_out, 13, "axis", "out_data", 1),
	Port_Property("width", 32, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("height", 32, hls_in, 15, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "sobel_rgb_axis";
