// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.470000,HLS_SYN_LAT=37,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=212,HLS_SYN_LUT=383,HLS_VERSION=2019_2}" *)

module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mat_a_0_0,
        mat_a_0_1,
        mat_a_1_0,
        mat_a_1_1,
        mat_b_0_0,
        mat_b_0_1,
        mat_b_1_0,
        mat_b_1_1,
        mat_c_0_0,
        mat_c_0_0_ap_vld,
        mat_c_0_1,
        mat_c_0_1_ap_vld,
        mat_c_1_0,
        mat_c_1_0_ap_vld,
        mat_c_1_1,
        mat_c_1_1_ap_vld
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] mat_a_0_0;
input  [31:0] mat_a_0_1;
input  [31:0] mat_a_1_0;
input  [31:0] mat_a_1_1;
input  [31:0] mat_b_0_0;
input  [31:0] mat_b_0_1;
input  [31:0] mat_b_1_0;
input  [31:0] mat_b_1_1;
output  [31:0] mat_c_0_0;
output   mat_c_0_0_ap_vld;
output  [31:0] mat_c_0_1;
output   mat_c_0_1_ap_vld;
output  [31:0] mat_c_1_0;
output   mat_c_1_0_ap_vld;
output  [31:0] mat_c_1_1;
output   mat_c_1_1_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg mat_c_0_0_ap_vld;
reg mat_c_0_1_ap_vld;
reg mat_c_1_0_ap_vld;
reg mat_c_1_1_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] r_fu_189_p2;
reg   [1:0] r_reg_284;
wire    ap_CS_fsm_state2;
wire   [0:0] trunc_ln32_fu_195_p1;
reg   [0:0] trunc_ln32_reg_289;
wire   [0:0] icmp_ln26_fu_183_p2;
wire   [1:0] c_fu_205_p2;
reg   [1:0] c_reg_297;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln28_fu_199_p2;
wire   [0:0] trunc_ln32_1_fu_211_p1;
reg   [0:0] trunc_ln32_1_reg_312;
wire   [31:0] select_ln32_2_fu_215_p3;
reg   [31:0] select_ln32_2_reg_326;
wire   [31:0] select_ln32_3_fu_223_p3;
reg   [31:0] select_ln32_3_reg_331;
wire   [1:0] p_fu_237_p2;
reg   [1:0] p_reg_339;
wire    ap_CS_fsm_state4;
wire  signed [31:0] select_ln32_4_fu_259_p3;
reg  signed [31:0] select_ln32_4_reg_344;
wire   [0:0] icmp_ln31_fu_231_p2;
wire  signed [31:0] select_ln32_5_fu_266_p3;
reg  signed [31:0] select_ln32_5_reg_349;
wire   [31:0] mul_ln32_fu_272_p2;
reg   [31:0] mul_ln32_reg_354;
wire    ap_CS_fsm_state5;
wire   [31:0] sum_fu_276_p2;
wire    ap_CS_fsm_state6;
reg   [1:0] r_0_reg_134;
reg   [1:0] c_0_reg_145;
reg   [31:0] sum_0_reg_156;
reg   [1:0] p_0_reg_172;
wire   [0:0] trunc_ln32_2_fu_243_p1;
wire   [31:0] select_ln32_fu_247_p3;
wire   [31:0] select_ln32_1_fu_253_p3;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln31_fu_231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        c_0_reg_145 <= c_reg_297;
    end else if (((icmp_ln26_fu_183_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        c_0_reg_145 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_0_reg_172 <= p_reg_339;
    end else if (((icmp_ln28_fu_199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_reg_172 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln28_fu_199_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        r_0_reg_134 <= r_reg_284;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        r_0_reg_134 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sum_0_reg_156 <= sum_fu_276_p2;
    end else if (((icmp_ln28_fu_199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        sum_0_reg_156 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        c_reg_297 <= c_fu_205_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mul_ln32_reg_354 <= mul_ln32_fu_272_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_reg_339 <= p_fu_237_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        r_reg_284 <= r_fu_189_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln28_fu_199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        select_ln32_2_reg_326 <= select_ln32_2_fu_215_p3;
        select_ln32_3_reg_331 <= select_ln32_3_fu_223_p3;
        trunc_ln32_1_reg_312 <= trunc_ln32_1_fu_211_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln31_fu_231_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        select_ln32_4_reg_344 <= select_ln32_4_fu_259_p3;
        select_ln32_5_reg_349 <= select_ln32_5_fu_266_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_183_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln32_reg_289 <= trunc_ln32_fu_195_p1;
    end
end

always @ (*) begin
    if (((icmp_ln26_fu_183_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln26_fu_183_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_231_p2 == 1'd1) & (trunc_ln32_1_reg_312 == 1'd0) & (trunc_ln32_reg_289 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        mat_c_0_0_ap_vld = 1'b1;
    end else begin
        mat_c_0_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_231_p2 == 1'd1) & (trunc_ln32_1_reg_312 == 1'd1) & (trunc_ln32_reg_289 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        mat_c_0_1_ap_vld = 1'b1;
    end else begin
        mat_c_0_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_231_p2 == 1'd1) & (trunc_ln32_1_reg_312 == 1'd0) & (trunc_ln32_reg_289 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        mat_c_1_0_ap_vld = 1'b1;
    end else begin
        mat_c_1_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_231_p2 == 1'd1) & (trunc_ln32_1_reg_312 == 1'd1) & (trunc_ln32_reg_289 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        mat_c_1_1_ap_vld = 1'b1;
    end else begin
        mat_c_1_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln26_fu_183_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln28_fu_199_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln31_fu_231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign c_fu_205_p2 = (c_0_reg_145 + 2'd1);

assign icmp_ln26_fu_183_p2 = ((r_0_reg_134 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_199_p2 = ((c_0_reg_145 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_231_p2 = ((p_0_reg_172 == 2'd2) ? 1'b1 : 1'b0);

assign mat_c_0_0 = sum_0_reg_156;

assign mat_c_0_1 = sum_0_reg_156;

assign mat_c_1_0 = sum_0_reg_156;

assign mat_c_1_1 = sum_0_reg_156;

assign mul_ln32_fu_272_p2 = ($signed(select_ln32_4_reg_344) * $signed(select_ln32_5_reg_349));

assign p_fu_237_p2 = (p_0_reg_172 + 2'd1);

assign r_fu_189_p2 = (r_0_reg_134 + 2'd1);

assign select_ln32_1_fu_253_p3 = ((trunc_ln32_2_fu_243_p1[0:0] === 1'b1) ? mat_a_0_1 : mat_a_0_0);

assign select_ln32_2_fu_215_p3 = ((trunc_ln32_1_fu_211_p1[0:0] === 1'b1) ? mat_b_1_1 : mat_b_1_0);

assign select_ln32_3_fu_223_p3 = ((trunc_ln32_1_fu_211_p1[0:0] === 1'b1) ? mat_b_0_1 : mat_b_0_0);

assign select_ln32_4_fu_259_p3 = ((trunc_ln32_reg_289[0:0] === 1'b1) ? select_ln32_fu_247_p3 : select_ln32_1_fu_253_p3);

assign select_ln32_5_fu_266_p3 = ((trunc_ln32_2_fu_243_p1[0:0] === 1'b1) ? select_ln32_2_reg_326 : select_ln32_3_reg_331);

assign select_ln32_fu_247_p3 = ((trunc_ln32_2_fu_243_p1[0:0] === 1'b1) ? mat_a_1_1 : mat_a_1_0);

assign sum_fu_276_p2 = (mul_ln32_reg_354 + sum_0_reg_156);

assign trunc_ln32_1_fu_211_p1 = c_0_reg_145[0:0];

assign trunc_ln32_2_fu_243_p1 = p_0_reg_172[0:0];

assign trunc_ln32_fu_195_p1 = r_0_reg_134[0:0];

endmodule //matrix_mult
