// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="stencil2d,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.388400,HLS_SYN_LAT=-1515119878,HLS_SYN_TPT=none,HLS_SYN_MEM=256,HLS_SYN_DSP=25,HLS_SYN_FF=5628,HLS_SYN_LUT=6988,HLS_VERSION=2019_2}" *)

module stencil2d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        surface_address0,
        surface_ce0,
        surface_q0,
        surface_address1,
        surface_ce1,
        surface_q1,
        output_surface_address0,
        output_surface_ce0,
        output_surface_we0,
        output_surface_d0,
        output_surface_q0,
        output_surface_address1,
        output_surface_ce1,
        output_surface_q1,
        target_time_s,
        dt,
        dx,
        diffusivity
);

parameter    ap_ST_fsm_state1 = 160'd1;
parameter    ap_ST_fsm_state2 = 160'd2;
parameter    ap_ST_fsm_state3 = 160'd4;
parameter    ap_ST_fsm_state4 = 160'd8;
parameter    ap_ST_fsm_state5 = 160'd16;
parameter    ap_ST_fsm_state6 = 160'd32;
parameter    ap_ST_fsm_state7 = 160'd64;
parameter    ap_ST_fsm_state8 = 160'd128;
parameter    ap_ST_fsm_state9 = 160'd256;
parameter    ap_ST_fsm_state10 = 160'd512;
parameter    ap_ST_fsm_state11 = 160'd1024;
parameter    ap_ST_fsm_state12 = 160'd2048;
parameter    ap_ST_fsm_state13 = 160'd4096;
parameter    ap_ST_fsm_state14 = 160'd8192;
parameter    ap_ST_fsm_state15 = 160'd16384;
parameter    ap_ST_fsm_state16 = 160'd32768;
parameter    ap_ST_fsm_state17 = 160'd65536;
parameter    ap_ST_fsm_state18 = 160'd131072;
parameter    ap_ST_fsm_state19 = 160'd262144;
parameter    ap_ST_fsm_state20 = 160'd524288;
parameter    ap_ST_fsm_state21 = 160'd1048576;
parameter    ap_ST_fsm_state22 = 160'd2097152;
parameter    ap_ST_fsm_state23 = 160'd4194304;
parameter    ap_ST_fsm_state24 = 160'd8388608;
parameter    ap_ST_fsm_state25 = 160'd16777216;
parameter    ap_ST_fsm_state26 = 160'd33554432;
parameter    ap_ST_fsm_state27 = 160'd67108864;
parameter    ap_ST_fsm_state28 = 160'd134217728;
parameter    ap_ST_fsm_state29 = 160'd268435456;
parameter    ap_ST_fsm_state30 = 160'd536870912;
parameter    ap_ST_fsm_state31 = 160'd1073741824;
parameter    ap_ST_fsm_state32 = 160'd2147483648;
parameter    ap_ST_fsm_state33 = 160'd4294967296;
parameter    ap_ST_fsm_state34 = 160'd8589934592;
parameter    ap_ST_fsm_state35 = 160'd17179869184;
parameter    ap_ST_fsm_state36 = 160'd34359738368;
parameter    ap_ST_fsm_state37 = 160'd68719476736;
parameter    ap_ST_fsm_state38 = 160'd137438953472;
parameter    ap_ST_fsm_state39 = 160'd274877906944;
parameter    ap_ST_fsm_state40 = 160'd549755813888;
parameter    ap_ST_fsm_state41 = 160'd1099511627776;
parameter    ap_ST_fsm_state42 = 160'd2199023255552;
parameter    ap_ST_fsm_state43 = 160'd4398046511104;
parameter    ap_ST_fsm_state44 = 160'd8796093022208;
parameter    ap_ST_fsm_state45 = 160'd17592186044416;
parameter    ap_ST_fsm_state46 = 160'd35184372088832;
parameter    ap_ST_fsm_state47 = 160'd70368744177664;
parameter    ap_ST_fsm_state48 = 160'd140737488355328;
parameter    ap_ST_fsm_state49 = 160'd281474976710656;
parameter    ap_ST_fsm_state50 = 160'd562949953421312;
parameter    ap_ST_fsm_state51 = 160'd1125899906842624;
parameter    ap_ST_fsm_state52 = 160'd2251799813685248;
parameter    ap_ST_fsm_state53 = 160'd4503599627370496;
parameter    ap_ST_fsm_state54 = 160'd9007199254740992;
parameter    ap_ST_fsm_state55 = 160'd18014398509481984;
parameter    ap_ST_fsm_state56 = 160'd36028797018963968;
parameter    ap_ST_fsm_state57 = 160'd72057594037927936;
parameter    ap_ST_fsm_state58 = 160'd144115188075855872;
parameter    ap_ST_fsm_state59 = 160'd288230376151711744;
parameter    ap_ST_fsm_state60 = 160'd576460752303423488;
parameter    ap_ST_fsm_state61 = 160'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 160'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 160'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 160'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 160'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 160'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 160'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 160'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 160'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 160'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 160'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 160'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 160'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 160'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 160'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 160'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 160'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 160'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 160'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 160'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 160'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 160'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 160'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 160'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 160'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 160'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 160'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 160'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 160'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 160'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 160'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 160'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 160'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 160'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 160'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 160'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 160'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 160'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 160'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 160'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 160'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 160'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 160'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 160'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 160'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 160'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 160'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 160'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 160'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 160'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 160'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 160'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 160'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 160'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 160'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 160'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 160'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 160'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 160'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 160'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 160'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 160'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 160'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 160'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 160'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 160'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 160'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 160'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 160'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state130 = 160'd680564733841876926926749214863536422912;
parameter    ap_ST_fsm_state131 = 160'd1361129467683753853853498429727072845824;
parameter    ap_ST_fsm_state132 = 160'd2722258935367507707706996859454145691648;
parameter    ap_ST_fsm_state133 = 160'd5444517870735015415413993718908291383296;
parameter    ap_ST_fsm_state134 = 160'd10889035741470030830827987437816582766592;
parameter    ap_ST_fsm_state135 = 160'd21778071482940061661655974875633165533184;
parameter    ap_ST_fsm_state136 = 160'd43556142965880123323311949751266331066368;
parameter    ap_ST_fsm_state137 = 160'd87112285931760246646623899502532662132736;
parameter    ap_ST_fsm_state138 = 160'd174224571863520493293247799005065324265472;
parameter    ap_ST_fsm_state139 = 160'd348449143727040986586495598010130648530944;
parameter    ap_ST_fsm_state140 = 160'd696898287454081973172991196020261297061888;
parameter    ap_ST_fsm_state141 = 160'd1393796574908163946345982392040522594123776;
parameter    ap_ST_fsm_state142 = 160'd2787593149816327892691964784081045188247552;
parameter    ap_ST_fsm_state143 = 160'd5575186299632655785383929568162090376495104;
parameter    ap_ST_fsm_state144 = 160'd11150372599265311570767859136324180752990208;
parameter    ap_ST_fsm_state145 = 160'd22300745198530623141535718272648361505980416;
parameter    ap_ST_fsm_state146 = 160'd44601490397061246283071436545296723011960832;
parameter    ap_ST_fsm_state147 = 160'd89202980794122492566142873090593446023921664;
parameter    ap_ST_fsm_state148 = 160'd178405961588244985132285746181186892047843328;
parameter    ap_ST_fsm_state149 = 160'd356811923176489970264571492362373784095686656;
parameter    ap_ST_fsm_state150 = 160'd713623846352979940529142984724747568191373312;
parameter    ap_ST_fsm_state151 = 160'd1427247692705959881058285969449495136382746624;
parameter    ap_ST_fsm_state152 = 160'd2854495385411919762116571938898990272765493248;
parameter    ap_ST_fsm_state153 = 160'd5708990770823839524233143877797980545530986496;
parameter    ap_ST_fsm_state154 = 160'd11417981541647679048466287755595961091061972992;
parameter    ap_ST_fsm_state155 = 160'd22835963083295358096932575511191922182123945984;
parameter    ap_ST_fsm_state156 = 160'd45671926166590716193865151022383844364247891968;
parameter    ap_ST_fsm_state157 = 160'd91343852333181432387730302044767688728495783936;
parameter    ap_ST_fsm_state158 = 160'd182687704666362864775460604089535377456991567872;
parameter    ap_ST_fsm_state159 = 160'd365375409332725729550921208179070754913983135744;
parameter    ap_ST_fsm_state160 = 160'd730750818665451459101842416358141509827966271488;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] surface_address0;
output   surface_ce0;
input  [63:0] surface_q0;
output  [15:0] surface_address1;
output   surface_ce1;
input  [63:0] surface_q1;
output  [15:0] output_surface_address0;
output   output_surface_ce0;
output   output_surface_we0;
output  [63:0] output_surface_d0;
input  [63:0] output_surface_q0;
output  [15:0] output_surface_address1;
output   output_surface_ce1;
input  [63:0] output_surface_q1;
input  [63:0] target_time_s;
input  [63:0] dt;
input  [63:0] dx;
input  [63:0] diffusivity;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] surface_address0;
reg surface_ce0;
reg[15:0] surface_address1;
reg surface_ce1;
reg[15:0] output_surface_address0;
reg output_surface_ce0;
reg output_surface_we0;
reg[63:0] output_surface_d0;
reg[15:0] output_surface_address1;
reg output_surface_ce1;

(* fsm_encoding = "none" *) reg   [159:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] grp_fu_366_p2;
reg   [63:0] reg_383;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state43;
wire    ap_CS_fsm_state76;
wire    ap_CS_fsm_state144;
wire   [63:0] grp_fu_372_p2;
reg   [63:0] reg_390;
reg   [63:0] reg_396;
wire    ap_CS_fsm_state52;
wire    ap_CS_fsm_state58;
wire    ap_CS_fsm_state64;
wire    ap_CS_fsm_state70;
wire   [63:0] grp_fu_361_p2;
reg   [63:0] reg_404;
wire    ap_CS_fsm_state82;
wire    ap_CS_fsm_state89;
wire    ap_CS_fsm_state132;
wire    ap_CS_fsm_state138;
wire    ap_CS_fsm_state156;
reg   [63:0] reg_413;
wire    ap_CS_fsm_state126;
reg   [63:0] reg_420;
wire   [63:0] grp_fu_379_p2;
reg   [63:0] r_reg_1003;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state49;
reg   [63:0] tmp_3_reg_1013;
wire   [8:0] y_fu_432_p2;
reg   [8:0] y_reg_1022;
wire    ap_CS_fsm_state50;
wire   [17:0] zext_ln15_fu_446_p1;
reg   [17:0] zext_ln15_reg_1027;
wire   [0:0] icmp_ln15_fu_426_p2;
wire   [17:0] zext_ln21_fu_458_p1;
reg   [17:0] zext_ln21_reg_1034;
wire  signed [17:0] sext_ln16_fu_476_p1;
reg  signed [17:0] sext_ln16_reg_1039;
wire   [8:0] x_fu_486_p2;
reg   [8:0] x_reg_1047;
wire    ap_CS_fsm_state51;
wire   [0:0] icmp_ln16_fu_480_p2;
reg   [15:0] surface_addr_4_reg_1063;
reg   [15:0] output_surface_addr_reg_1068;
reg   [63:0] surface_load_1_reg_1079;
wire    ap_CS_fsm_state57;
wire   [17:0] add_ln21_7_fu_586_p2;
reg   [17:0] add_ln21_7_reg_1089;
wire    ap_CS_fsm_state63;
reg   [63:0] x_assign_reg_1099;
wire    ap_CS_fsm_state120;
reg   [0:0] p_Result_s_reg_1104;
wire    ap_CS_fsm_state121;
wire   [31:0] p_Val2_5_fu_716_p3;
reg   [31:0] p_Val2_5_reg_1109;
wire   [31:0] p_Val2_6_fu_729_p3;
reg   [31:0] p_Val2_6_reg_1115;
wire    ap_CS_fsm_state122;
wire   [30:0] step_num_fu_744_p2;
reg   [30:0] step_num_reg_1123;
wire    ap_CS_fsm_state123;
wire   [7:0] y_1_fu_756_p2;
reg   [7:0] y_1_reg_1131;
wire    ap_CS_fsm_state124;
wire   [0:0] icmp_ln38_fu_750_p2;
wire   [7:0] add_ln41_fu_762_p2;
reg   [7:0] add_ln41_reg_1137;
wire   [16:0] sub_ln41_fu_792_p2;
reg   [16:0] sub_ln41_reg_1142;
wire    ap_CS_fsm_state125;
wire   [0:0] icmp_ln39_fu_798_p2;
wire   [7:0] x_1_fu_828_p2;
reg   [7:0] x_1_reg_1160;
wire    ap_CS_fsm_state131;
wire    ap_CS_fsm_state137;
wire   [16:0] add_ln41_4_fu_883_p2;
reg   [16:0] add_ln41_4_reg_1180;
reg   [63:0] tmp_14_reg_1185;
wire    ap_CS_fsm_state150;
wire   [16:0] sub_ln49_fu_928_p2;
reg   [16:0] sub_ln49_reg_1193;
wire    ap_CS_fsm_state158;
wire   [0:0] icmp_ln46_fu_892_p2;
wire    ap_CS_fsm_state159;
wire   [0:0] icmp_ln47_fu_934_p2;
wire   [7:0] y_2_fu_960_p2;
wire   [7:0] x_2_fu_979_p2;
wire    ap_CS_fsm_state160;
reg   [15:0] surface_store_address0;
reg    surface_store_ce0;
reg    surface_store_we0;
wire   [63:0] surface_store_q0;
reg   [8:0] y_0_reg_266;
reg   [8:0] x_0_reg_278;
wire    ap_CS_fsm_state84;
reg   [63:0] storemerge_reg_290;
wire   [0:0] empty_11_fu_557_p2;
wire   [0:0] empty_8_fu_539_p2;
wire    ap_CS_fsm_state83;
reg   [30:0] step_num_0_reg_302;
reg   [7:0] y1_0_reg_313;
wire   [0:0] icmp_ln31_fu_739_p2;
reg   [7:0] x2_0_reg_325;
wire    ap_CS_fsm_state157;
reg   [7:0] y3_0_reg_337;
reg   [7:0] x4_0_reg_349;
wire   [63:0] zext_ln21_2_fu_501_p1;
wire  signed [63:0] sext_ln21_fu_511_p1;
wire   [63:0] zext_ln21_3_fu_521_p1;
wire   [63:0] zext_ln21_5_fu_571_p1;
wire   [63:0] zext_ln21_7_fu_591_p1;
wire   [63:0] zext_ln41_2_fu_811_p1;
wire   [63:0] zext_ln41_3_fu_823_p1;
wire   [63:0] zext_ln41_5_fu_842_p1;
wire   [63:0] zext_ln41_4_fu_855_p1;
wire   [63:0] zext_ln41_7_fu_878_p1;
wire  signed [63:0] sext_ln41_fu_888_p1;
wire  signed [63:0] sext_ln49_fu_955_p1;
wire   [63:0] zext_ln49_3_fu_974_p1;
wire    ap_CS_fsm_state69;
reg   [63:0] grp_fu_361_p0;
reg   [63:0] grp_fu_361_p1;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state53;
wire    ap_CS_fsm_state59;
wire    ap_CS_fsm_state65;
wire    ap_CS_fsm_state77;
wire    ap_CS_fsm_state127;
wire    ap_CS_fsm_state133;
wire    ap_CS_fsm_state139;
wire    ap_CS_fsm_state151;
reg   [63:0] grp_fu_366_p0;
reg   [63:0] grp_fu_366_p1;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state71;
wire    ap_CS_fsm_state145;
reg   [63:0] grp_fu_372_p0;
reg   [63:0] grp_fu_372_p1;
reg   [63:0] grp_fu_379_p0;
reg   [63:0] grp_fu_379_p1;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state90;
wire   [16:0] tmp_18_fu_438_p3;
wire   [16:0] tmp_19_fu_450_p3;
wire   [8:0] add_ln21_fu_462_p2;
wire   [16:0] tmp_20_fu_468_p3;
wire   [17:0] zext_ln21_1_fu_492_p1;
wire   [17:0] add_ln21_3_fu_496_p2;
wire   [17:0] add_ln21_4_fu_506_p2;
wire   [17:0] add_ln21_5_fu_516_p2;
wire   [0:0] empty_7_fu_533_p2;
wire   [0:0] empty_fu_527_p2;
wire   [0:0] empty_10_fu_551_p2;
wire   [0:0] empty_9_fu_545_p2;
wire   [17:0] zext_ln21_4_fu_563_p1;
wire   [17:0] add_ln21_6_fu_566_p2;
wire   [8:0] add_ln21_2_fu_576_p2;
wire   [17:0] zext_ln21_6_fu_582_p1;
wire   [63:0] p_Val2_s_fu_595_p1;
wire   [51:0] tmp_V_1_fu_616_p1;
wire   [53:0] mantissa_V_fu_620_p4;
wire   [10:0] tmp_V_fu_606_p4;
wire   [11:0] zext_ln502_fu_634_p1;
wire   [11:0] add_ln502_fu_638_p2;
wire   [10:0] sub_ln1311_fu_652_p2;
wire   [0:0] isNeg_fu_644_p3;
wire  signed [11:0] sext_ln1311_fu_658_p1;
wire   [11:0] ush_fu_662_p3;
wire  signed [31:0] sext_ln1311_1_fu_670_p1;
wire   [53:0] zext_ln1285_fu_678_p1;
wire   [136:0] zext_ln682_fu_630_p1;
wire   [136:0] zext_ln1287_fu_674_p1;
wire   [53:0] r_V_fu_682_p2;
wire   [0:0] tmp_33_fu_694_p3;
wire   [136:0] r_V_1_fu_688_p2;
wire   [31:0] zext_ln662_fu_702_p1;
wire   [31:0] tmp_17_fu_706_p4;
wire   [31:0] result_V_1_fu_724_p2;
wire   [31:0] zext_ln31_fu_735_p1;
wire   [15:0] tmp_21_fu_768_p3;
wire   [8:0] tmp_22_fu_780_p3;
wire   [16:0] zext_ln41_fu_776_p1;
wire   [16:0] zext_ln41_1_fu_788_p1;
wire   [15:0] tmp_25_fu_804_p3;
wire   [15:0] tmp_26_fu_816_p3;
wire   [15:0] tmp_28_fu_834_p3;
wire   [15:0] tmp_27_fu_847_p3;
wire   [7:0] add_ln41_2_fu_860_p2;
wire   [15:0] tmp_29_fu_870_p3;
wire   [16:0] zext_ln41_6_fu_866_p1;
wire   [7:0] add_ln49_fu_898_p2;
wire   [15:0] tmp_23_fu_904_p3;
wire   [8:0] tmp_24_fu_916_p3;
wire   [16:0] zext_ln49_fu_912_p1;
wire   [16:0] zext_ln49_1_fu_924_p1;
wire   [7:0] add_ln49_1_fu_940_p2;
wire   [16:0] zext_ln49_2_fu_946_p1;
wire   [16:0] add_ln49_2_fu_950_p2;
wire   [15:0] tmp_30_fu_966_p3;
reg   [1:0] grp_fu_361_opcode;
reg   [159:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 160'd1;
end

stencil2d_surfacebkb #(
    .DataWidth( 64 ),
    .AddressRange( 64516 ),
    .AddressWidth( 16 ))
surface_store_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(surface_store_address0),
    .ce0(surface_store_ce0),
    .we0(surface_store_we0),
    .d0(reg_404),
    .q0(surface_store_q0)
);

stencil2d_dadddsucud #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
stencil2d_dadddsucud_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_361_p0),
    .din1(grp_fu_361_p1),
    .opcode(grp_fu_361_opcode),
    .ce(1'b1),
    .dout(grp_fu_361_p2)
);

stencil2d_dmul_64dEe #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
stencil2d_dmul_64dEe_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_366_p0),
    .din1(grp_fu_366_p1),
    .ce(1'b1),
    .dout(grp_fu_366_p2)
);

stencil2d_dmul_64dEe #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
stencil2d_dmul_64dEe_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_372_p0),
    .din1(grp_fu_372_p1),
    .ce(1'b1),
    .dout(grp_fu_372_p2)
);

stencil2d_ddiv_64eOg #(
    .ID( 1 ),
    .NUM_STAGE( 31 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
stencil2d_ddiv_64eOg_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_379_p0),
    .din1(grp_fu_379_p1),
    .ce(1'b1),
    .dout(grp_fu_379_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        reg_396 <= surface_q1;
    end else if (((1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state52))) begin
        reg_396 <= surface_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state132)) begin
        reg_413 <= output_surface_q1;
    end else if (((1'b1 == ap_CS_fsm_state126) | (1'b1 == ap_CS_fsm_state138))) begin
        reg_413 <= output_surface_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_892_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state158))) begin
        step_num_0_reg_302 <= step_num_reg_1123;
    end else if ((1'b1 == ap_CS_fsm_state122)) begin
        step_num_0_reg_302 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state83)) begin
        storemerge_reg_290 <= reg_404;
    end else if (((1'b1 == ap_CS_fsm_state51) & (((empty_8_fu_539_p2 == 1'd1) & (icmp_ln16_fu_480_p2 == 1'd0)) | ((empty_11_fu_557_p2 == 1'd1) & (icmp_ln16_fu_480_p2 == 1'd0))))) begin
        storemerge_reg_290 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_750_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state124))) begin
        x2_0_reg_325 <= 8'd1;
    end else if ((1'b1 == ap_CS_fsm_state157)) begin
        x2_0_reg_325 <= x_1_reg_1160;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_892_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state158))) begin
        x4_0_reg_349 <= 8'd1;
    end else if ((1'b1 == ap_CS_fsm_state160)) begin
        x4_0_reg_349 <= x_2_fu_979_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_fu_426_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state50))) begin
        x_0_reg_278 <= 9'd0;
    end else if ((1'b1 == ap_CS_fsm_state84)) begin
        x_0_reg_278 <= x_reg_1047;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_798_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state125))) begin
        y1_0_reg_313 <= y_1_reg_1131;
    end else if (((icmp_ln31_fu_739_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state123))) begin
        y1_0_reg_313 <= 8'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_750_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state124))) begin
        y3_0_reg_337 <= 8'd1;
    end else if (((icmp_ln47_fu_934_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state159))) begin
        y3_0_reg_337 <= y_2_fu_960_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_fu_480_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state51))) begin
        y_0_reg_266 <= y_reg_1022;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        y_0_reg_266 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        add_ln21_7_reg_1089 <= add_ln21_7_fu_586_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state137)) begin
        add_ln41_4_reg_1180 <= add_ln41_4_fu_883_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_750_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state124))) begin
        add_ln41_reg_1137 <= add_ln41_fu_762_p2;
        sub_ln41_reg_1142[16 : 1] <= sub_ln41_fu_792_p2[16 : 1];
        y_1_reg_1131 <= y_1_fu_756_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_fu_480_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state51))) begin
        output_surface_addr_reg_1068 <= zext_ln21_3_fu_521_p1;
        surface_addr_4_reg_1063 <= zext_ln21_3_fu_521_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state121)) begin
        p_Result_s_reg_1104 <= p_Val2_s_fu_595_p1[32'd63];
        p_Val2_5_reg_1109 <= p_Val2_5_fu_716_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state122)) begin
        p_Val2_6_reg_1115 <= p_Val2_6_fu_729_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        r_reg_1003 <= grp_fu_379_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state144) | (1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state6))) begin
        reg_383 <= grp_fu_366_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state6))) begin
        reg_390 <= grp_fu_372_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state156) | (1'b1 == ap_CS_fsm_state138) | (1'b1 == ap_CS_fsm_state132) | (1'b1 == ap_CS_fsm_state89) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state144))) begin
        reg_404 <= grp_fu_361_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state126) | (1'b1 == ap_CS_fsm_state138))) begin
        reg_420 <= output_surface_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_fu_426_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state50))) begin
        sext_ln16_reg_1039[17 : 8] <= sext_ln16_fu_476_p1[17 : 8];
        zext_ln15_reg_1027[16 : 8] <= zext_ln15_fu_446_p1[16 : 8];
        zext_ln21_reg_1034[16 : 8] <= zext_ln21_fu_458_p1[16 : 8];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state123)) begin
        step_num_reg_1123 <= step_num_fu_744_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_892_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state158))) begin
        sub_ln49_reg_1193[16 : 1] <= sub_ln49_fu_928_p2[16 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        surface_load_1_reg_1079 <= surface_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state150)) begin
        tmp_14_reg_1185 <= grp_fu_366_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        tmp_3_reg_1013 <= grp_fu_361_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state131)) begin
        x_1_reg_1160 <= x_1_fu_828_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state120)) begin
        x_assign_reg_1099 <= grp_fu_379_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        x_reg_1047 <= x_fu_486_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        y_reg_1022 <= y_fu_432_p2;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_739_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state123))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_739_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state123))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state44) | ((icmp_ln15_fu_426_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state50)))) begin
        grp_fu_361_opcode = 2'd1;
    end else if (((1'b1 == ap_CS_fsm_state151) | (1'b1 == ap_CS_fsm_state139) | (1'b1 == ap_CS_fsm_state133) | (1'b1 == ap_CS_fsm_state127) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state53))) begin
        grp_fu_361_opcode = 2'd0;
    end else begin
        grp_fu_361_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state151)) begin
        grp_fu_361_p0 = tmp_14_reg_1185;
    end else if ((1'b1 == ap_CS_fsm_state127)) begin
        grp_fu_361_p0 = reg_413;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        grp_fu_361_p0 = reg_383;
    end else if (((1'b1 == ap_CS_fsm_state139) | (1'b1 == ap_CS_fsm_state133) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state59))) begin
        grp_fu_361_p0 = reg_404;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        grp_fu_361_p0 = reg_396;
    end else if ((1'b1 == ap_CS_fsm_state50)) begin
        grp_fu_361_p0 = target_time_s;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_361_p0 = 64'd4607182418800017408;
    end else begin
        grp_fu_361_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state139) | (1'b1 == ap_CS_fsm_state133))) begin
        grp_fu_361_p1 = reg_413;
    end else if ((1'b1 == ap_CS_fsm_state127)) begin
        grp_fu_361_p1 = reg_420;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        grp_fu_361_p1 = reg_390;
    end else if (((1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state59))) begin
        grp_fu_361_p1 = reg_396;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        grp_fu_361_p1 = surface_load_1_reg_1079;
    end else if ((1'b1 == ap_CS_fsm_state50)) begin
        grp_fu_361_p1 = dt;
    end else if (((1'b1 == ap_CS_fsm_state151) | (1'b1 == ap_CS_fsm_state44))) begin
        grp_fu_361_p1 = reg_383;
    end else begin
        grp_fu_361_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state139)) begin
        grp_fu_366_p0 = tmp_3_reg_1013;
    end else if (((1'b1 == ap_CS_fsm_state145) | (1'b1 == ap_CS_fsm_state71) | (1'b1 == ap_CS_fsm_state38))) begin
        grp_fu_366_p0 = r_reg_1003;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_366_p0 = diffusivity;
    end else begin
        grp_fu_366_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state139)) begin
        grp_fu_366_p1 = reg_420;
    end else if (((1'b1 == ap_CS_fsm_state145) | (1'b1 == ap_CS_fsm_state71))) begin
        grp_fu_366_p1 = reg_404;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_366_p1 = 64'd4616189618054758400;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_366_p1 = dt;
    end else begin
        grp_fu_366_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state71)) begin
        grp_fu_372_p0 = tmp_3_reg_1013;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_372_p0 = dx;
    end else begin
        grp_fu_372_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state71)) begin
        grp_fu_372_p1 = reg_396;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_372_p1 = dx;
    end else begin
        grp_fu_372_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_379_p0 = reg_404;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_379_p0 = reg_383;
    end else begin
        grp_fu_379_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_379_p1 = dt;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_379_p1 = reg_390;
    end else begin
        grp_fu_379_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state160)) begin
        output_surface_address0 = zext_ln49_3_fu_974_p1;
    end else if ((1'b1 == ap_CS_fsm_state137)) begin
        output_surface_address0 = zext_ln41_7_fu_878_p1;
    end else if ((1'b1 == ap_CS_fsm_state125)) begin
        output_surface_address0 = zext_ln41_2_fu_811_p1;
    end else if ((1'b1 == ap_CS_fsm_state84)) begin
        output_surface_address0 = output_surface_addr_reg_1068;
    end else begin
        output_surface_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state137)) begin
        output_surface_address1 = zext_ln41_4_fu_855_p1;
    end else if ((1'b1 == ap_CS_fsm_state131)) begin
        output_surface_address1 = zext_ln41_5_fu_842_p1;
    end else if ((1'b1 == ap_CS_fsm_state125)) begin
        output_surface_address1 = zext_ln41_3_fu_823_p1;
    end else begin
        output_surface_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state160) | (1'b1 == ap_CS_fsm_state137) | (1'b1 == ap_CS_fsm_state125))) begin
        output_surface_ce0 = 1'b1;
    end else begin
        output_surface_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state137) | (1'b1 == ap_CS_fsm_state131) | (1'b1 == ap_CS_fsm_state125))) begin
        output_surface_ce1 = 1'b1;
    end else begin
        output_surface_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state160)) begin
        output_surface_d0 = surface_store_q0;
    end else if ((1'b1 == ap_CS_fsm_state84)) begin
        output_surface_d0 = storemerge_reg_290;
    end else begin
        output_surface_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state160))) begin
        output_surface_we0 = 1'b1;
    end else begin
        output_surface_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        surface_address0 = surface_addr_4_reg_1063;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        surface_address0 = zext_ln21_5_fu_571_p1;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        surface_address0 = zext_ln21_2_fu_501_p1;
    end else begin
        surface_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state63)) begin
        surface_address1 = zext_ln21_7_fu_591_p1;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        surface_address1 = sext_ln21_fu_511_p1;
    end else begin
        surface_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state69) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state51))) begin
        surface_ce0 = 1'b1;
    end else begin
        surface_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state51))) begin
        surface_ce1 = 1'b1;
    end else begin
        surface_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state159)) begin
        surface_store_address0 = sext_ln49_fu_955_p1;
    end else if ((1'b1 == ap_CS_fsm_state157)) begin
        surface_store_address0 = sext_ln41_fu_888_p1;
    end else begin
        surface_store_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state157) | (1'b1 == ap_CS_fsm_state159))) begin
        surface_store_ce0 = 1'b1;
    end else begin
        surface_store_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state157)) begin
        surface_store_we0 = 1'b1;
    end else begin
        surface_store_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            if (((icmp_ln15_fu_426_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state50))) begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state85;
            end
        end
        ap_ST_fsm_state51 : begin
            if (((icmp_ln16_fu_480_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state51))) begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end else if (((1'b1 == ap_CS_fsm_state51) & (((empty_8_fu_539_p2 == 1'd1) & (icmp_ln16_fu_480_p2 == 1'd0)) | ((empty_11_fu_557_p2 == 1'd1) & (icmp_ln16_fu_480_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state84;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state52;
            end
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            if (((icmp_ln31_fu_739_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state123))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state124;
            end
        end
        ap_ST_fsm_state124 : begin
            if (((icmp_ln38_fu_750_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state124))) begin
                ap_NS_fsm = ap_ST_fsm_state158;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state125;
            end
        end
        ap_ST_fsm_state125 : begin
            if (((icmp_ln39_fu_798_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state125))) begin
                ap_NS_fsm = ap_ST_fsm_state124;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state126;
            end
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state130;
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state131;
        end
        ap_ST_fsm_state131 : begin
            ap_NS_fsm = ap_ST_fsm_state132;
        end
        ap_ST_fsm_state132 : begin
            ap_NS_fsm = ap_ST_fsm_state133;
        end
        ap_ST_fsm_state133 : begin
            ap_NS_fsm = ap_ST_fsm_state134;
        end
        ap_ST_fsm_state134 : begin
            ap_NS_fsm = ap_ST_fsm_state135;
        end
        ap_ST_fsm_state135 : begin
            ap_NS_fsm = ap_ST_fsm_state136;
        end
        ap_ST_fsm_state136 : begin
            ap_NS_fsm = ap_ST_fsm_state137;
        end
        ap_ST_fsm_state137 : begin
            ap_NS_fsm = ap_ST_fsm_state138;
        end
        ap_ST_fsm_state138 : begin
            ap_NS_fsm = ap_ST_fsm_state139;
        end
        ap_ST_fsm_state139 : begin
            ap_NS_fsm = ap_ST_fsm_state140;
        end
        ap_ST_fsm_state140 : begin
            ap_NS_fsm = ap_ST_fsm_state141;
        end
        ap_ST_fsm_state141 : begin
            ap_NS_fsm = ap_ST_fsm_state142;
        end
        ap_ST_fsm_state142 : begin
            ap_NS_fsm = ap_ST_fsm_state143;
        end
        ap_ST_fsm_state143 : begin
            ap_NS_fsm = ap_ST_fsm_state144;
        end
        ap_ST_fsm_state144 : begin
            ap_NS_fsm = ap_ST_fsm_state145;
        end
        ap_ST_fsm_state145 : begin
            ap_NS_fsm = ap_ST_fsm_state146;
        end
        ap_ST_fsm_state146 : begin
            ap_NS_fsm = ap_ST_fsm_state147;
        end
        ap_ST_fsm_state147 : begin
            ap_NS_fsm = ap_ST_fsm_state148;
        end
        ap_ST_fsm_state148 : begin
            ap_NS_fsm = ap_ST_fsm_state149;
        end
        ap_ST_fsm_state149 : begin
            ap_NS_fsm = ap_ST_fsm_state150;
        end
        ap_ST_fsm_state150 : begin
            ap_NS_fsm = ap_ST_fsm_state151;
        end
        ap_ST_fsm_state151 : begin
            ap_NS_fsm = ap_ST_fsm_state152;
        end
        ap_ST_fsm_state152 : begin
            ap_NS_fsm = ap_ST_fsm_state153;
        end
        ap_ST_fsm_state153 : begin
            ap_NS_fsm = ap_ST_fsm_state154;
        end
        ap_ST_fsm_state154 : begin
            ap_NS_fsm = ap_ST_fsm_state155;
        end
        ap_ST_fsm_state155 : begin
            ap_NS_fsm = ap_ST_fsm_state156;
        end
        ap_ST_fsm_state156 : begin
            ap_NS_fsm = ap_ST_fsm_state157;
        end
        ap_ST_fsm_state157 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state158 : begin
            if (((icmp_ln46_fu_892_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state158))) begin
                ap_NS_fsm = ap_ST_fsm_state123;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state159;
            end
        end
        ap_ST_fsm_state159 : begin
            if (((icmp_ln47_fu_934_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state159))) begin
                ap_NS_fsm = ap_ST_fsm_state158;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state160;
            end
        end
        ap_ST_fsm_state160 : begin
            ap_NS_fsm = ap_ST_fsm_state159;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_2_fu_576_p2 = ($signed(x_0_reg_278) + $signed(9'd511));

assign add_ln21_3_fu_496_p2 = (zext_ln21_reg_1034 + zext_ln21_1_fu_492_p1);

assign add_ln21_4_fu_506_p2 = ($signed(sext_ln16_reg_1039) + $signed(zext_ln21_1_fu_492_p1));

assign add_ln21_5_fu_516_p2 = (zext_ln15_reg_1027 + zext_ln21_1_fu_492_p1);

assign add_ln21_6_fu_566_p2 = (zext_ln15_reg_1027 + zext_ln21_4_fu_563_p1);

assign add_ln21_7_fu_586_p2 = (zext_ln15_reg_1027 + zext_ln21_6_fu_582_p1);

assign add_ln21_fu_462_p2 = ($signed(y_0_reg_266) + $signed(9'd511));

assign add_ln41_2_fu_860_p2 = ($signed(x2_0_reg_325) + $signed(8'd255));

assign add_ln41_4_fu_883_p2 = (sub_ln41_reg_1142 + zext_ln41_6_fu_866_p1);

assign add_ln41_fu_762_p2 = ($signed(y1_0_reg_313) + $signed(8'd255));

assign add_ln49_1_fu_940_p2 = ($signed(x4_0_reg_349) + $signed(8'd255));

assign add_ln49_2_fu_950_p2 = (sub_ln49_reg_1193 + zext_ln49_2_fu_946_p1);

assign add_ln49_fu_898_p2 = ($signed(y3_0_reg_337) + $signed(8'd255));

assign add_ln502_fu_638_p2 = ($signed(12'd3073) + $signed(zext_ln502_fu_634_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state120 = ap_CS_fsm[32'd119];

assign ap_CS_fsm_state121 = ap_CS_fsm[32'd120];

assign ap_CS_fsm_state122 = ap_CS_fsm[32'd121];

assign ap_CS_fsm_state123 = ap_CS_fsm[32'd122];

assign ap_CS_fsm_state124 = ap_CS_fsm[32'd123];

assign ap_CS_fsm_state125 = ap_CS_fsm[32'd124];

assign ap_CS_fsm_state126 = ap_CS_fsm[32'd125];

assign ap_CS_fsm_state127 = ap_CS_fsm[32'd126];

assign ap_CS_fsm_state131 = ap_CS_fsm[32'd130];

assign ap_CS_fsm_state132 = ap_CS_fsm[32'd131];

assign ap_CS_fsm_state133 = ap_CS_fsm[32'd132];

assign ap_CS_fsm_state137 = ap_CS_fsm[32'd136];

assign ap_CS_fsm_state138 = ap_CS_fsm[32'd137];

assign ap_CS_fsm_state139 = ap_CS_fsm[32'd138];

assign ap_CS_fsm_state144 = ap_CS_fsm[32'd143];

assign ap_CS_fsm_state145 = ap_CS_fsm[32'd144];

assign ap_CS_fsm_state150 = ap_CS_fsm[32'd149];

assign ap_CS_fsm_state151 = ap_CS_fsm[32'd150];

assign ap_CS_fsm_state156 = ap_CS_fsm[32'd155];

assign ap_CS_fsm_state157 = ap_CS_fsm[32'd156];

assign ap_CS_fsm_state158 = ap_CS_fsm[32'd157];

assign ap_CS_fsm_state159 = ap_CS_fsm[32'd158];

assign ap_CS_fsm_state160 = ap_CS_fsm[32'd159];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state63 = ap_CS_fsm[32'd62];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state82 = ap_CS_fsm[32'd81];

assign ap_CS_fsm_state83 = ap_CS_fsm[32'd82];

assign ap_CS_fsm_state84 = ap_CS_fsm[32'd83];

assign ap_CS_fsm_state89 = ap_CS_fsm[32'd88];

assign ap_CS_fsm_state90 = ap_CS_fsm[32'd89];

assign empty_10_fu_551_p2 = ((x_0_reg_278 == 9'd0) ? 1'b1 : 1'b0);

assign empty_11_fu_557_p2 = (empty_9_fu_545_p2 | empty_10_fu_551_p2);

assign empty_7_fu_533_p2 = ((y_0_reg_266 == 9'd0) ? 1'b1 : 1'b0);

assign empty_8_fu_539_p2 = (empty_fu_527_p2 | empty_7_fu_533_p2);

assign empty_9_fu_545_p2 = ((x_0_reg_278 == 9'd255) ? 1'b1 : 1'b0);

assign empty_fu_527_p2 = ((y_0_reg_266 == 9'd255) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_426_p2 = ((y_0_reg_266 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_480_p2 = ((x_0_reg_278 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_739_p2 = (($signed(zext_ln31_fu_735_p1) < $signed(p_Val2_6_reg_1115)) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_750_p2 = ((y1_0_reg_313 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_798_p2 = ((x2_0_reg_325 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_892_p2 = ((y3_0_reg_337 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_934_p2 = ((x4_0_reg_349 == 8'd255) ? 1'b1 : 1'b0);

assign isNeg_fu_644_p3 = add_ln502_fu_638_p2[32'd11];

assign mantissa_V_fu_620_p4 = {{{{1'd1}, {tmp_V_1_fu_616_p1}}}, {1'd0}};

assign p_Val2_5_fu_716_p3 = ((isNeg_fu_644_p3[0:0] === 1'b1) ? zext_ln662_fu_702_p1 : tmp_17_fu_706_p4);

assign p_Val2_6_fu_729_p3 = ((p_Result_s_reg_1104[0:0] === 1'b1) ? result_V_1_fu_724_p2 : p_Val2_5_reg_1109);

assign p_Val2_s_fu_595_p1 = x_assign_reg_1099;

assign r_V_1_fu_688_p2 = zext_ln682_fu_630_p1 << zext_ln1287_fu_674_p1;

assign r_V_fu_682_p2 = mantissa_V_fu_620_p4 >> zext_ln1285_fu_678_p1;

assign result_V_1_fu_724_p2 = (32'd0 - p_Val2_5_reg_1109);

assign sext_ln1311_1_fu_670_p1 = $signed(ush_fu_662_p3);

assign sext_ln1311_fu_658_p1 = $signed(sub_ln1311_fu_652_p2);

assign sext_ln16_fu_476_p1 = $signed(tmp_20_fu_468_p3);

assign sext_ln21_fu_511_p1 = $signed(add_ln21_4_fu_506_p2);

assign sext_ln41_fu_888_p1 = $signed(add_ln41_4_reg_1180);

assign sext_ln49_fu_955_p1 = $signed(add_ln49_2_fu_950_p2);

assign step_num_fu_744_p2 = (step_num_0_reg_302 + 31'd1);

assign sub_ln1311_fu_652_p2 = (11'd1023 - tmp_V_fu_606_p4);

assign sub_ln41_fu_792_p2 = (zext_ln41_fu_776_p1 - zext_ln41_1_fu_788_p1);

assign sub_ln49_fu_928_p2 = (zext_ln49_fu_912_p1 - zext_ln49_1_fu_924_p1);

assign tmp_17_fu_706_p4 = {{r_V_1_fu_688_p2[84:53]}};

assign tmp_18_fu_438_p3 = {{y_0_reg_266}, {8'd0}};

assign tmp_19_fu_450_p3 = {{y_fu_432_p2}, {8'd0}};

assign tmp_20_fu_468_p3 = {{add_ln21_fu_462_p2}, {8'd0}};

assign tmp_21_fu_768_p3 = {{add_ln41_fu_762_p2}, {8'd0}};

assign tmp_22_fu_780_p3 = {{add_ln41_fu_762_p2}, {1'd0}};

assign tmp_23_fu_904_p3 = {{add_ln49_fu_898_p2}, {8'd0}};

assign tmp_24_fu_916_p3 = {{add_ln49_fu_898_p2}, {1'd0}};

assign tmp_25_fu_804_p3 = {{y_1_reg_1131}, {x2_0_reg_325}};

assign tmp_26_fu_816_p3 = {{add_ln41_reg_1137}, {x2_0_reg_325}};

assign tmp_27_fu_847_p3 = {{y1_0_reg_313}, {x2_0_reg_325}};

assign tmp_28_fu_834_p3 = {{y1_0_reg_313}, {x_1_fu_828_p2}};

assign tmp_29_fu_870_p3 = {{y1_0_reg_313}, {add_ln41_2_fu_860_p2}};

assign tmp_30_fu_966_p3 = {{y3_0_reg_337}, {x4_0_reg_349}};

assign tmp_33_fu_694_p3 = r_V_fu_682_p2[32'd53];

assign tmp_V_1_fu_616_p1 = p_Val2_s_fu_595_p1[51:0];

assign tmp_V_fu_606_p4 = {{p_Val2_s_fu_595_p1[62:52]}};

assign ush_fu_662_p3 = ((isNeg_fu_644_p3[0:0] === 1'b1) ? sext_ln1311_fu_658_p1 : add_ln502_fu_638_p2);

assign x_1_fu_828_p2 = (x2_0_reg_325 + 8'd1);

assign x_2_fu_979_p2 = (x4_0_reg_349 + 8'd1);

assign x_fu_486_p2 = (x_0_reg_278 + 9'd1);

assign y_1_fu_756_p2 = (y1_0_reg_313 + 8'd1);

assign y_2_fu_960_p2 = (y3_0_reg_337 + 8'd1);

assign y_fu_432_p2 = (y_0_reg_266 + 9'd1);

assign zext_ln1285_fu_678_p1 = $unsigned(sext_ln1311_1_fu_670_p1);

assign zext_ln1287_fu_674_p1 = $unsigned(sext_ln1311_1_fu_670_p1);

assign zext_ln15_fu_446_p1 = tmp_18_fu_438_p3;

assign zext_ln21_1_fu_492_p1 = x_0_reg_278;

assign zext_ln21_2_fu_501_p1 = add_ln21_3_fu_496_p2;

assign zext_ln21_3_fu_521_p1 = add_ln21_5_fu_516_p2;

assign zext_ln21_4_fu_563_p1 = x_reg_1047;

assign zext_ln21_5_fu_571_p1 = add_ln21_6_fu_566_p2;

assign zext_ln21_6_fu_582_p1 = add_ln21_2_fu_576_p2;

assign zext_ln21_7_fu_591_p1 = add_ln21_7_reg_1089;

assign zext_ln21_fu_458_p1 = tmp_19_fu_450_p3;

assign zext_ln31_fu_735_p1 = step_num_0_reg_302;

assign zext_ln41_1_fu_788_p1 = tmp_22_fu_780_p3;

assign zext_ln41_2_fu_811_p1 = tmp_25_fu_804_p3;

assign zext_ln41_3_fu_823_p1 = tmp_26_fu_816_p3;

assign zext_ln41_4_fu_855_p1 = tmp_27_fu_847_p3;

assign zext_ln41_5_fu_842_p1 = tmp_28_fu_834_p3;

assign zext_ln41_6_fu_866_p1 = add_ln41_2_fu_860_p2;

assign zext_ln41_7_fu_878_p1 = tmp_29_fu_870_p3;

assign zext_ln41_fu_776_p1 = tmp_21_fu_768_p3;

assign zext_ln49_1_fu_924_p1 = tmp_24_fu_916_p3;

assign zext_ln49_2_fu_946_p1 = add_ln49_1_fu_940_p2;

assign zext_ln49_3_fu_974_p1 = tmp_30_fu_966_p3;

assign zext_ln49_fu_912_p1 = tmp_23_fu_904_p3;

assign zext_ln502_fu_634_p1 = tmp_V_fu_606_p4;

assign zext_ln662_fu_702_p1 = tmp_33_fu_694_p3;

assign zext_ln682_fu_630_p1 = mantissa_V_fu_620_p4;

always @ (posedge ap_clk) begin
    zext_ln15_reg_1027[7:0] <= 8'b00000000;
    zext_ln15_reg_1027[17] <= 1'b0;
    zext_ln21_reg_1034[7:0] <= 8'b00000000;
    zext_ln21_reg_1034[17] <= 1'b0;
    sext_ln16_reg_1039[7:0] <= 8'b00000000;
    sub_ln41_reg_1142[0] <= 1'b0;
    sub_ln49_reg_1193[0] <= 1'b0;
end

endmodule //stencil2d
