-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mat_a_0_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    mat_a_0_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    mat_a_1_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    mat_a_1_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    mat_b_0_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    mat_b_0_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    mat_b_1_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    mat_b_1_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    mat_c_0_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_c_0_0_ap_vld : OUT STD_LOGIC;
    mat_c_0_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_c_0_1_ap_vld : OUT STD_LOGIC;
    mat_c_1_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_c_1_0_ap_vld : OUT STD_LOGIC;
    mat_c_1_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_c_1_1_ap_vld : OUT STD_LOGIC );
end;


architecture behav of matrix_mult is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.470000,HLS_SYN_LAT=37,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=212,HLS_SYN_LUT=383,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal r_fu_189_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal r_reg_284 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln32_fu_195_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln32_reg_289 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_fu_183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_fu_205_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal c_reg_297 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln28_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln32_1_fu_211_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln32_1_reg_312 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln32_2_fu_215_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln32_2_reg_326 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln32_3_fu_223_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln32_3_reg_331 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_fu_237_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_reg_339 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal select_ln32_4_fu_259_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln32_4_reg_344 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln31_fu_231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln32_5_fu_266_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln32_5_reg_349 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln32_fu_272_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln32_reg_354 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal sum_fu_276_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal r_0_reg_134 : STD_LOGIC_VECTOR (1 downto 0);
    signal c_0_reg_145 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum_0_reg_156 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_reg_172 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln32_2_fu_243_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln32_fu_247_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln32_1_fu_253_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    c_0_reg_145_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln31_fu_231_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                c_0_reg_145 <= c_reg_297;
            elsif (((icmp_ln26_fu_183_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                c_0_reg_145 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    p_0_reg_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                p_0_reg_172 <= p_reg_339;
            elsif (((icmp_ln28_fu_199_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                p_0_reg_172 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    r_0_reg_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln28_fu_199_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                r_0_reg_134 <= r_reg_284;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                r_0_reg_134 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    sum_0_reg_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                sum_0_reg_156 <= sum_fu_276_p2;
            elsif (((icmp_ln28_fu_199_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                sum_0_reg_156 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                c_reg_297 <= c_fu_205_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                mul_ln32_reg_354 <= mul_ln32_fu_272_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                p_reg_339 <= p_fu_237_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                r_reg_284 <= r_fu_189_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln28_fu_199_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                select_ln32_2_reg_326 <= select_ln32_2_fu_215_p3;
                select_ln32_3_reg_331 <= select_ln32_3_fu_223_p3;
                trunc_ln32_1_reg_312 <= trunc_ln32_1_fu_211_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln31_fu_231_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                select_ln32_4_reg_344 <= select_ln32_4_fu_259_p3;
                select_ln32_5_reg_349 <= select_ln32_5_fu_266_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_fu_183_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                trunc_ln32_reg_289 <= trunc_ln32_fu_195_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln26_fu_183_p2, ap_CS_fsm_state3, icmp_ln28_fu_199_p2, ap_CS_fsm_state4, icmp_ln31_fu_231_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln26_fu_183_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln28_fu_199_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln31_fu_231_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln26_fu_183_p2)
    begin
        if (((icmp_ln26_fu_183_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln26_fu_183_p2)
    begin
        if (((icmp_ln26_fu_183_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    c_fu_205_p2 <= std_logic_vector(unsigned(c_0_reg_145) + unsigned(ap_const_lv2_1));
    icmp_ln26_fu_183_p2 <= "1" when (r_0_reg_134 = ap_const_lv2_2) else "0";
    icmp_ln28_fu_199_p2 <= "1" when (c_0_reg_145 = ap_const_lv2_2) else "0";
    icmp_ln31_fu_231_p2 <= "1" when (p_0_reg_172 = ap_const_lv2_2) else "0";
    mat_c_0_0 <= sum_0_reg_156;

    mat_c_0_0_ap_vld_assign_proc : process(trunc_ln32_reg_289, trunc_ln32_1_reg_312, ap_CS_fsm_state4, icmp_ln31_fu_231_p2)
    begin
        if (((icmp_ln31_fu_231_p2 = ap_const_lv1_1) and (trunc_ln32_1_reg_312 = ap_const_lv1_0) and (trunc_ln32_reg_289 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            mat_c_0_0_ap_vld <= ap_const_logic_1;
        else 
            mat_c_0_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mat_c_0_1 <= sum_0_reg_156;

    mat_c_0_1_ap_vld_assign_proc : process(trunc_ln32_reg_289, trunc_ln32_1_reg_312, ap_CS_fsm_state4, icmp_ln31_fu_231_p2)
    begin
        if (((icmp_ln31_fu_231_p2 = ap_const_lv1_1) and (trunc_ln32_1_reg_312 = ap_const_lv1_1) and (trunc_ln32_reg_289 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            mat_c_0_1_ap_vld <= ap_const_logic_1;
        else 
            mat_c_0_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mat_c_1_0 <= sum_0_reg_156;

    mat_c_1_0_ap_vld_assign_proc : process(trunc_ln32_reg_289, trunc_ln32_1_reg_312, ap_CS_fsm_state4, icmp_ln31_fu_231_p2)
    begin
        if (((icmp_ln31_fu_231_p2 = ap_const_lv1_1) and (trunc_ln32_1_reg_312 = ap_const_lv1_0) and (trunc_ln32_reg_289 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            mat_c_1_0_ap_vld <= ap_const_logic_1;
        else 
            mat_c_1_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mat_c_1_1 <= sum_0_reg_156;

    mat_c_1_1_ap_vld_assign_proc : process(trunc_ln32_reg_289, trunc_ln32_1_reg_312, ap_CS_fsm_state4, icmp_ln31_fu_231_p2)
    begin
        if (((icmp_ln31_fu_231_p2 = ap_const_lv1_1) and (trunc_ln32_1_reg_312 = ap_const_lv1_1) and (trunc_ln32_reg_289 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            mat_c_1_1_ap_vld <= ap_const_logic_1;
        else 
            mat_c_1_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln32_fu_272_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(select_ln32_4_reg_344) * signed(select_ln32_5_reg_349))), 32));
    p_fu_237_p2 <= std_logic_vector(unsigned(p_0_reg_172) + unsigned(ap_const_lv2_1));
    r_fu_189_p2 <= std_logic_vector(unsigned(r_0_reg_134) + unsigned(ap_const_lv2_1));
    select_ln32_1_fu_253_p3 <= 
        mat_a_0_1 when (trunc_ln32_2_fu_243_p1(0) = '1') else 
        mat_a_0_0;
    select_ln32_2_fu_215_p3 <= 
        mat_b_1_1 when (trunc_ln32_1_fu_211_p1(0) = '1') else 
        mat_b_1_0;
    select_ln32_3_fu_223_p3 <= 
        mat_b_0_1 when (trunc_ln32_1_fu_211_p1(0) = '1') else 
        mat_b_0_0;
    select_ln32_4_fu_259_p3 <= 
        select_ln32_fu_247_p3 when (trunc_ln32_reg_289(0) = '1') else 
        select_ln32_1_fu_253_p3;
    select_ln32_5_fu_266_p3 <= 
        select_ln32_2_reg_326 when (trunc_ln32_2_fu_243_p1(0) = '1') else 
        select_ln32_3_reg_331;
    select_ln32_fu_247_p3 <= 
        mat_a_1_1 when (trunc_ln32_2_fu_243_p1(0) = '1') else 
        mat_a_1_0;
    sum_fu_276_p2 <= std_logic_vector(unsigned(mul_ln32_reg_354) + unsigned(sum_0_reg_156));
    trunc_ln32_1_fu_211_p1 <= c_0_reg_145(1 - 1 downto 0);
    trunc_ln32_2_fu_243_p1 <= p_0_reg_172(1 - 1 downto 0);
    trunc_ln32_fu_195_p1 <= r_0_reg_134(1 - 1 downto 0);
end behav;
